### DISCUSSION TITLE
Network Attachment Definition CRD name with dashes

### DISCUSSION THREAD

**Discussion by maze88** [k8snetworkplumbingwg/multus-cni#1249] [General]
The [Network Attachment Definition CRD name](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset.yml#L13) (and [singular/plural names](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset.yml#L18-L19)) `network-attachment-definitions.k8s.cni.cncf.io` contains dashes, something that I don't believe is common in Kubernetes resource type naming (just try running `kubectl api-resources | cut -d ' ' -f 1` and then look for items with dashes...).

The obvious fix would be to change the actual CRD names.

However, it's important to keep in mind that such a change could _potentially_ break various things _downstream_ (if they're "delicate" enough)... This could be partially mitigated by adding pseudo-backwards-compatibility by supporting the "old" (with dashes) plural/singular names via [the `shortNames` list](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset.yml#L21).

Here is my suggested implementation in the YAML:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkattachmentdefinitions.k8s.cni.cncf.io  # removed dashes
spec:
  group: k8s.cni.cncf.io
  scope: Namespaced
  names:
    plural: networkattachmentdefinitions   # removed dashes
    singular: networkattachmentdefinition  # removed dashes
    kind: NetworkAttachmentDefinition
    shortNames:
    - net-attach-def
    - network-attachment-definition   # pseudo-backwards-compatibility
    - network-attachment-definitions  # pseudo-backwards-compatibility
    - nad                             # additional *shorter* short name, worth adding too ;)
# ...
```

This is far from a critical issue, but still worth bringing up IMHO...

Some additional info on CRD naming conventions and defaults can be reviewed in [these reference docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#customresourcedefinitionnames-v1-apiextensions-k8s-io).
