### ISSUE TITLE
net1 default-route config deleted eth0 default route ?

### ISSUE THREAD

**Issue by abmybgx** [k8snetworkplumbingwg/multus-cni#1011]
**What happend**:
When I did not use default-route, my pod routes were like below.
```
annotations:
    k8s.v1.cni.cncf.io/networks: plat-boson-service/test-b4
```
![image](https://user-images.githubusercontent.com/34848440/210718687-36f75a5e-70fd-4fdc-a8bd-c8d84177c382.png)

I'd like to keep eth0 default route only, so I used default-route to set the net1 default route to empty, but eth0 default route was also deleted.
```
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{ "name":"test-b4",
         "namespace": "plat-boson-service",
         "default-route": []
      }]
```
![image](https://user-images.githubusercontent.com/34848440/210719493-2fee449d-df1f-42ef-9964-1664d4883654.png)

**What you expected to happen**:

Keep eth0 default route, and clear net1 default route.

**How to reproduce it (as minimally and precisely as possible)**:

Based on below env.

**Environment**:

- Multus version 
  ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick
- Kubernetes version (use `kubectl version`): v1.21.5
- Primary CNI for Kubernetes cluster: kube-ovn v1.9.3
- OS (e.g. from /etc/os-release): CentOS 7
- File of '/etc/cni/net.d/'
```
[root@HOST-10-111-41-11 bao]# ls /etc/cni/net.d
00-multus.conf  01-kube-ovn.conflist  multus.d
```
- File of '/etc/cni/multus/net.d'
```
[root@HOST-10-111-41-11 bao]# ls /etc/cni/net.d/multus.d/
multus.kubeconfig
```
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`) 
```
# nad
# routes and gateway config was no use on my test case
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: st.com/mlnx_sriov_rdma
  name:  test-b4
  namespace: plat-boson-service
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "sriov",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "test-b4.plat-boson-service",
        "routes": [{ "dst": "10.119.11.0/24" }],
        "gateway": "10.119.11.1"
      }
    }'
```
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [{ "name":"test-b4",
         "namespace": "plat-boson-service",
         "default-route": []
      }]
  name: test-b43
spec:
  containers:
  - command:
    - sh
    - -c
    - |
      ls -l /dev/infiniband /sys/class/infiniband /sys/class/net
      sleep 1000000
    image: registry.st.com/kube-ovn/golang:1.16-cuda10-cudnn7-gcc49-ubuntu20.04-devel
    imagePullPolicy: IfNotPresent
    name: sriov-test-1
    resources:
      limits:
        sensetime.com/mlnx_sriov_rdma: "1"
      requests:
        sensetime.com/mlnx_sriov_rdma: "1"
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
  nodeName: host-10-111-41-13-10.111.41.13
```
- Other log outputs (if you use multus logging)
