### ISSUE TITLE
thick daemon does not start or log anything

### ISSUE THREAD

**Issue by aluveitie** [k8snetworkplumbingwg/multus-cni#1071]
I tried following the quick start guide to set up the thick daemonset on my k3s cluster.

```
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: multus-daemon-config
        namespace: kube-system
        labels:
          app: multus
      data:
        daemon-config.json: |
          {
              "chrootDir": "/hostroot",
              "confDir": "/host/etc/cni/net.d",
              "logLevel": "debug",
              "socketDir": "/host/run/multus/",
              "cniVersion": "1.0.0",
              "cniConfigDir": "/host/etc/cni/net.d",
              "multusConfigFile": "auto",
              "multusAutoconfigDir": "/host/etc/cni/net.d",
              "clusterNetwork": "/host/etc/cni/net.d/10-flannel.conflist",
              "kubeconfig": "/host/etc/cni/net.d/multus.d/multus.kubeconfig"
          }
```

```
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: multus
        namespace: kube-system
        labels:
          tier: node
          app: multus
          name: multus
      spec:
        selector:
          matchLabels:
            name: multus
        updateStrategy:
          type: RollingUpdate
        template:
          metadata:
            labels:
              tier: node
              app: multus
              name: multus
          spec:
            hostNetwork: true
            hostPID: true
            tolerations:
              - operator: Exists
                effect: NoSchedule
              - operator: Exists
                effect: NoExecute
            serviceAccountName: multus
            containers:
              - name: kube-multus
                image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.0-alpha
                command: [ "/usr/src/multus-cni/bin/multus-daemon" ]
                resources:
                  requests:
                    cpu: "100m"
                    memory: "50Mi"
                  limits:
                    cpu: "150m"
                    memory: "75Mi"
                securityContext:
                  privileged: true
                volumeMounts:
                  - name: cni
                    mountPath: /host/etc/cni/net.d
                  - name: cnibin
                    mountPath: /host/opt/cni/bin
                  - name: host-run
                    mountPath: /host/run
                  - name: host-var-lib-cni-multus
                    mountPath: /var/lib/cni/multus
                  - name: host-var-lib-kubelet
                    mountPath: /var/lib/kubelet
                  - name: host-run-k8s-cni-cncf-io
                    mountPath: /run/k8s.cni.cncf.io
                  - name: host-run-netns
                    mountPath: /run/netns
                    mountPropagation: HostToContainer
                  - name: multus-daemon-config
                    mountPath: /etc/cni/net.d/multus.d
                    readOnly: true
                  - name: hostroot
                    mountPath: /hostroot
                    mountPropagation: HostToContainer
            initContainers:
              - name: install-multus-binary
                image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.0-alpha
                command:
                  - "cp"
                  - "/usr/src/multus-cni/bin/multus-shim"
                  - "/host/opt/cni/bin/multus-shim"
                resources:
                  requests:
                    cpu: "10m"
                    memory: "15Mi"
                securityContext:
                  privileged: true
                volumeMounts:
                  - name: cnibin
                    mountPath: /host/opt/cni/bin
                    mountPropagation: Bidirectional
            terminationGracePeriodSeconds: 10
            volumes:
              - name: cni
                hostPath:
                  path: /var/lib/rancher/k3s/agent/etc/cni/net.d
              - name: cnibin
                hostPath:
                  path: /var/lib/rancher/k3s/data/current/bin
              - name: hostroot
                hostPath:
                  path: /
              - name: multus-daemon-config
                configMap:
                  name: multus-daemon-config
                  items:
                    - key: daemon-config.json
                      path: daemon-config.json
              - name: host-run
                hostPath:
                  path: /run
              - name: host-var-lib-cni-multus
                hostPath:
                  path: /var/lib/cni/multus
              - name: host-var-lib-kubelet
                hostPath:
                  path: /var/lib/kubelet
              - name: host-run-k8s-cni-cncf-io
                hostPath:
                  path: /run/k8s.cni.cncf.io
              - name: host-run-netns
                hostPath:
                  path: /run/netns/
```

But `multus-daemon` does not seem to do anything. Neither the 00-multus.conf is created nor does it output anything. The pods then restart after the probe times out.
