### ISSUE TITLE
 IPv4 default route not getting added with static, sbr plugin

### ISSUE THREAD

**Issue by nknkgithub** [k8snetworkplumbingwg/multus-cni#1081]
**What happend**: 
Using multus CNI, with sriov plugin. For IP and route assignment static IPAM and sbr plugin is used. But default route is not getting added in routing table

**What you expected to happen**:
Default route needs to be added in autogenerated routing table number 

**How to reproduce it (as minimally and precisely as possible)**:

Below NAD and pod yaml is applied in k8s cluster

NAD file
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-test
  annotations:
    k8s.v1.cni.cncf.io/resourceName: "intel.com/pci_sriov_net_physnet0"
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "sriov-test",
      "plugins": [
        {
          "type": "sriov",
          "vlan": 961,
          "ipam": {
            "type": "static",
             "routes": [
              { "dst": "0.0.0.0/0", "gw": "10.210.106.254"}
            ]
     }
    },
    {
        "name": "sriov-test-sbr",
        "type": "sbr"
    }
    ]
   }'
```
Pod file
```
apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
                { "name": "sriov-test" ,
                  "ips": ["10.210.106.204/24"],
                  "interface": "test"}

        ]'
spec:
  containers:
  - name: sriov-example
    image: "<image>"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    resources:
      requests:
        memory: 1Gi
        intel.com/pci_sriov_net_physnet0: '1'
      limits:
        memory: 1Gi
        intel.com/pci_sriov_net_physnet0: '1'
    command: ["sleep", "infinity"]

  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations

```
**default route is not added in routing table 100**
```
sh-4.2# ip rule list
0:      from all lookup local
32765:  from 10.210.106.204 lookup 100
32766:  from all lookup main
32767:  from all lookup default

sh-4.2# ip r s
default via 169.254.1.1 dev eth0
169.254.1.1 dev eth0 scope link

sh-4.2# ip r s t 100
10.210.106.0/24 dev test proto kernel scope link src 10.210.106.204

```

**Anything else we need to know?**:
**Expected route**
```
default via 10.210.106.254 dev test
```

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
 ` multus-cni:v3.9.2`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"archive", BuildDate:"2022-12-19T07:54:12Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Primary CNI for Kubernetes cluster:
**Calico**

- OS (e.g. from /etc/os-release):
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
