### ISSUE TITLE
Unable to access 'networks-status' from Annotations in Pod Environment Variables

### ISSUE THREAD

**Issue by graydovee** [k8snetworkplumbingwg/multus-cni#1113]
**What happend**:
I want to get network-status in my program within Pod. so I set env and try to get from annotation. it not work and I get a empty env, but it can work fine when use any initContainer or recreate the container(e.g. use shell `sh -c '[ -z "$NETWORK_STATUS" ] && exit 1 || ./myProgram.exe'`)

**What you expected to happen**:
the env should work when the container first started

**How to reproduce it (as minimally and precisely as possible)**:
Env is empty in this pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotation:
    k8s.v1.cni.cncf.io/networks: network/mycni@mycni0
  name: demo
spec:
  containers:
  - env:
    - name: NETWORK_STATUS 
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['k8s.v1.cni.cncf.io/network-status']
    image: nginx:1.20
    name: nginx
```

It is work
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotation:
    k8s.v1.cni.cncf.io/networks: network/mycni@mycni0
  name: demo
spec:
  containers:
  - command:
    - sh
    - -c
    - '[ -z "$NETWORK_STATUS" ] && exit 1 || while true; do sleep 1; done'
    env:
    - name: NETWORK_STATUS 
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['k8s.v1.cni.cncf.io/network-status']
    image:  busybox:1.28.4
    name: demo
```

It is work, too
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotation:
    k8s.v1.cni.cncf.io/networks: network/mycni@mycni0
  name: demo
spec:
  containers:
  - env:
    - name: NETWORK_STATUS 
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['k8s.v1.cni.cncf.io/network-status']
    image: nginx:1.20
    name: nginx
  initContainers: 
  - command:
    - sleep	
    - 1s
    image: busybox:1.28.4
```

**Anything else we need to know?**:

**Environment**:

- Multus version v3.7.2
- Kubernetes version (use `kubectl version`): v1.21.12
- Primary CNI for Kubernetes cluster: flannel
- OS (e.g. from /etc/os-release): Ubuntu 18.04.6
