### ISSUE TITLE
[k3s] Custom cni-conf.json silently ends daemon processes

### ISSUE THREAD

**Issue by SuperCoolAlan** [k8snetworkplumbingwg/multus-cni#1143]
**What happend**:
After stabilizing a k3s deployment of Multus with `--multus-conf-file=auto`, mounting in a custom cni-conf.json via ConfigMap results in shortened logs from the Multus container as if the process is interrupted right after consuming the config.

**What you expected to happen**:
Changing `--multus-conf-file=auto` to `--multus-conf-file=/tmp/multus-conf/00-multus.conf` would consume my custom config and return error or continue running.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create and run a k3s image with the flags `--k3s-arg '--flannel-backend=none@server:*' \`   and `--k3s-arg '--disable-network-policy@server:*' \`. 
2. To this container, install [CNI network plugins](https://github.com/containernetworking/plugins) at `/opt/cni/bin`.
3. Install [Flannel CNI](https://github.com/flannel-io/flannel).
4. Install Multus CNI and provide the following args in the DaemonSet config:
```
        - "--multus-log-level=verbose"
        - "--multus-conf-file=auto"
        - "--multus-autoconfig-dir=/host/etc/cni/net.d"
        - "--cni-conf-dir=/host/etc/cni/net.d"
        - "--multus-kubeconfig-file-host=/etc/cni/net.d/multus.d/multus.kubeconfig"
```
5. Define custom config 00-multus.conf as:
```
    {
      "name": "multus-cni-network",
      "type": "multus",
      "logLevel": "verbose",
      "readinessindicatorfile": "/run/flannel/subnet.env",
      "capabilities": {
        "portMappings": true
      },
      "delegates": [
        {
          "cniVersion": "0.3.1",
          "name": "default-cni-network",
          "plugins": [
            {
              "type": "flannel",
              "name": "flannel.1",
                "delegate": {
                  "isDefaultGateway": true,
                  "hairpinMode": true
                }
              },
              {
                "type": "portmap",
                "capabilities": {
                  "portMappings": true
                }
              }
          ]
        }
      ],
    }
```
6. Enable custom config with replacing flag  "--multus-conf-file=/tmp/multus-conf/00-multus.conf". I have assured that the file is passed to this directory in the container.

**Anything else we need to know?**:
I have attempted to replace the config with examples found in the repo, and with the config file that appears when I have `--multus-conf-file=auto`. When set to a custom configuration, no kubeconfig file is created and logs only contain the following info:
```
multus config file /tmp/multus-conf/00-multus.conf is copied.
```

For reference, this is what appears in logs when in `auto` mode:
```
kubeconfig is created in /host/etc/cni/net.d/multus.d/multus.kubeconfig
kubeconfig file is created.
master capabilities is get from conflist
multus config file is created.
```

**Environment**:

- Multus version: v4.0.2
- image path and image ID (from 'docker images'): ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.2 (35afff607637)
- Kubernetes version (use `kubectl version`):
```
clientVersion:
  buildDate: "2023-06-14T09:53:42Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2022-06-13T19:57:53Z"
  compiler: gc
  gitCommit: efc5f1e9ee5a3e7f2d3f9accbfb4fe45d17bcfdd
  gitTreeState: clean
  gitVersion: v1.21.13+k3s1
  goVersion: go1.16.10
  major: "1"
  minor: "21"
  platform: linux/amd64
```

- Primary CNI for Kubernetes cluster: Flannel
- OS (e.g. from /etc/os-release): k3s v1.21.13-k3s1
- File of '/etc/cni/net.d/': custom 00-multus.conf defined above
- File of '/etc/cni/multus/net.d': DNE

**Comment by SuperCoolAlan** [comment]
Seems similar to https://github.com/k8snetworkplumbingwg/multus-cni/issues/688 and https://github.com/k8snetworkplumbingwg/multus-cni/issues/697

**Comment by nicklesimba** [comment]
Please ask the k3s community about issues with this environment

**Comment by SuperCoolAlan** [comment]
We have been able to work around this issue :smile: The following configurations were used to stabilize the thin deployment's DaemonSet on k3s after a version bump to `v1.27.4+k3s1`. The `--multus-conf-file=auto` flag ended up being the only way I could stabilize it, though. In the following Helm template, the multus-config ConfigMap is not consumed by Multus. This configuration does not differ much from https://github.com/k8snetworkplumbingwg/helm-charts/blob/2f782b76912967f11694e3c44ba2e93817a0d6a2/multus/templates/daemonSet.yaml 

```yaml
{{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "16" ) }}
{{- if .Values.multus.manifests.daemonSet }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-multus-ds
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "multus.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: multus
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
{{- include "multus.labels" . | indent 8 }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/multus/configMap.yaml") . | sha256sum }}
    spec:
      priorityClassName: system-node-critical
      hostNetwork: true
      {{- with .Values.multus.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector: {{- toYaml .Values.multus.labels.nodeSelector | nindent 8 }}
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: {{ .Values.multus.serviceAccount.name }}
      initContainers:
        - name: install-multus-binary
          image: ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot
          command: ["/install_multus"]
          args:
            - "--type"
            - "thin"
          resources:
            requests:
              cpu: "10m"
              memory: "15Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
              # mountPropagation: Bidirectional
      containers:
      - name: kube-{{ .Chart.Name }}
        image: multus-cni
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ["/thin_entrypoint"]
        args:
        - "--multus-conf-file=auto" # /tmp/multus-conf/00-multus.conf OR auto
        - "--multus-autoconfig-dir=/host/etc/cni/net.d"
        - "--multus-log-level=verbose"
        - "--cni-conf-dir=/host/etc/cni/net.d"
        - "--multus-kubeconfig-file-host=/etc/cni/net.d/multus.d/multus.kubeconfig"
        {{- if .Values.multus.pod.resources.multus }}
        resources: {{- toYaml .Values.multus.pod.resources.multus | nindent 10 }}
        {{- end }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: host-var-lib-cni-multus
          mountPath: /var/lib/cni/multus
        {{- if .Values.multus.manifests.configMap }}
        - name: multus-cfg
          mountPath: /tmp/multus-conf
        {{- end }}
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: host-var-lib-cni-multus
          hostPath:
            path: /var/lib/cni/multus
        {{- if .Values.multus.manifests.configMap }}
        - name: multus-cfg
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version }}-multus-config
            items:
            - key: cni-conf.json
              path: 00-multus.conf
        {{- end }}
{{- end }}
{{- end }}
```

Cheers! :partying_face:
