### ISSUE TITLE
00-multus.conf nesting causes error 

### ISSUE THREAD

**Issue by clee** [k8snetworkplumbingwg/multus-cni#1162]
**What happend**: Pods using multus networkattachmentdefinitions failed to start after upgrading cluster from 1.26.9 to 1.27.2

**What you expected to happen**: Pods using multus networks should still work after upgrade

**How to reproduce it (as minimally and precisely as possible)**: Upgrade cluster with crio backend from kubernetes 1.27.9 to 1.27.2, I guess?

**Anything else we need to know?**: I think there's a bug in the multus code that decides when to generate a new 00-multus.conf.

I was able to get my pods working properly again by deleting the multus daemonset, manually deleting `/etc/cni/net.d/00-multus.conf` on each node, and re-adding the multus daemonset. The broken 00-multus.conf looked like: 
```json                    
{
  "cniVersion": "0.3.1",
  "name": "multus-cni-network",
  "type": "multus",
  "capabilities": {
    "portMappings": true
  },
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
  "delegates": [
    {
      "capabilities": {
        "portMappings": true
      },
      "cniVersion": "0.3.1",
      "delegates": [
        {
          "cniVersion": "0.3.1",
          "name": "cni0",
          "plugins": [
            {
              "delegate": {
                "hairpinMode": true,
                "isDefaultGateway": true
              },
              "type": "flannel"
            },
            {
              "capabilities": {
                "portMappings": true
              },
              "type": "portmap"
            }
          ]
        }
      ],
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
      "name": "multus-cni-network",
      "type": "multus"
    }
  ]
}
```

The working `00-multus.conf` generated after nuking and reinstalling the daemonset: 
```json
{
  "cniVersion": "0.3.1",
  "name": "multus-cni-network",
  "type": "multus",
  "capabilities": {
    "portMappings": true
  },
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
  "delegates": [
    {
      "cniVersion": "0.3.1",
      "name": "cni0",
      "plugins": [
        {
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          },
          "type": "flannel"
        },
        {
          "capabilities": {
            "portMappings": true
          },
          "type": "portmap"
        }
      ]
    }
  ]
}
```

Notice the lack of nested "multus"/"multus-cni-network".

**Environment**:

- Multus version `ghcr.io/k8snetworkplumbingwg/multus-cni:stable` `ed70b5729dced`
  - Kubernetes version (use `kubectl version`):  
> Client Version: v1.28.2
> Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
> Server Version: v1.28.2

- Primary CNI for Kubernetes cluster: flannel
- OS (e.g. from /etc/os-release): debian 12 bookworm
- File of '/etc/cni/net.d/': `00-multus.conf 10-flannel.conflist 100-crio-bridge.conflist 200-loopback.conflist multus.d`
- File of '/etc/cni/multus/multus.d': `multus.kubeconfig`
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`):  
```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: wireguard-conf
  namespace: selfhosted
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "cni1",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "10.10.11.0/24",
              "rangeStart": "10.10.11.2",
              "rangeEnd": "10.10.11.200"
            }
          ]
        ],
        "routes": [
          {
            "dst": "0.0.0.0/0",
            "gw": "10.10.11.1"
          }
        ],
        "dns": "10.10.13.188"
      }
    }
```
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`): *This is what it looks like when it's working properly*; when the nested-multus configuration is in effect, the pod fails to create.
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "cni0",
          "interface": "eth0",
          "ips": [
              "10.20.1.97"
          ],
          "mac": "4e:94:10:f5:fa:63",
          "default": true,
          "dns": {},
          "gateway": [
              "10.20.1.1"
          ]
      },{
          "name": "selfhosted/wireguard-conf",
          "interface": "net1",
          "ips": [
              "10.10.11.148"
          ],
          "mac": "62:1f:95:52:6c:0b",
          "dns": {},
          "gateway": [
              "10.10.11.1"
          ]
      }]
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name": "wireguard-conf",
        "namespace": "selfhosted",
        "interface": "net1",
        "default-route": ["10.10.11.1"]
      }]
``` 
- Other log outputs (if you use multus logging)
The log message I was seeing over and over looked like:
`error adding pod selfhosted_client-0 to CNI network \"multus-cni-network\": plugin type=\"multus\" name=\"multus-cni-network\" failed (add): [selfhosted/client-0/b874bce6-4655-4887-bee1-4a2843ccae2e:multus-cni-network]: error adding container to network \"multus-cni-network\": [selfhosted/client-0/b874bce6-4655-4887-bee1-4a2843ccae2e:wireguard-conf]: error adding container to network \"wireguard-conf\": DelegateAdd: cannot set \"bridge\" interface name to \"net1\": validateIfName: interface name net1 already exists" pod="selfhosted/client-0"`
