### ISSUE TITLE
Multus deployment files missing a volume

### ISSUE THREAD

**Issue by urbaman** [k8snetworkplumbingwg/multus-cni#1164]
Hi,

On a fresh kubeadm 1.28.2 single node (for the moment) cluster, multus fails with the following error

```
kubectl create -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml
customresourcedefinition.apiextensions.k8s.io/network-attachment-definitions.k8s.cni.cncf.io created
clusterrole.rbac.authorization.k8s.io/multus created
clusterrolebinding.rbac.authorization.k8s.io/multus created
serviceaccount/multus created
configmap/multus-daemon-config created
The DaemonSet "kube-multus-ds" is invalid: spec.template.spec.containers[0].volumeMounts[1].name: Not found: "cni-bin"
```

Even if Calico flawlessly installed and the cni directories exist and present other plugins:

```
sudo ls /etc/cni/net.d/
10-calico.conflist  calico-kubeconfig
```

```
sudo ls /opt/cni/bin/
bandwidth  bridge  calico  calico-ipam  dhcp  dummy  firewall  flannel  host-device  host-local  install  ipvlan  loopback  macvlan  portmap  ptp  sbr  static  tuning  vlan  vrf
```

What am I missing?

_Originally posted by @urbaman in https://github.com/k8snetworkplumbingwg/multus-cni/discussions/1163_

I found out that the cni-bin volumeMount in the Multus container is missing the relative Volume definition:

```
     volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: hostroot
          hostPath:
            path: /
        - name: multus-daemon-config
          configMap:
            name: multus-daemon-config
            items:
            - key: daemon-config.json
              path: daemon-config.json
        - name: host-run
          hostPath:
            path: /run
        - name: host-var-lib-cni-multus
          hostPath:
            path: /var/lib/cni/multus
        - name: host-var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: host-run-k8s-cni-cncf-io
          hostPath:
            path: /run/k8s.cni.cncf.io
        - name: host-run-netns
          hostPath:
            path: /run/netns/
```

Probably misspelld with the other cnibin Volume.

Once added, everything went smooth

```
kubectl create -f multus-daemonset-thick.yml
customresourcedefinition.apiextensions.k8s.io/network-attachment-definitions.k8s.cni.cncf.io created
clusterrole.rbac.authorization.k8s.io/multus created
clusterrolebinding.rbac.authorization.k8s.io/multus created
serviceaccount/multus created
configmap/multus-daemon-config created
daemonset.apps/kube-multus-ds created
```
