### ISSUE TITLE
macvlan not working on the second interface

### ISSUE THREAD

**Issue by LiamLea** [k8snetworkplumbingwg/multus-cni#1183]
### Description
I have two interfaces which are in the same subnet. If i configure macvlan on the first interface it works while if configure macvlan on the second interface it doesn't work
### interfaces info
  * the host is a VM on the openstack and the two ports have disabled port secutiry
  * the two ports are both in the `10.172.1.0/24` subnet
```shell
$ ip a

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:51:6a:ef brd ff:ff:ff:ff:ff:ff
    inet 10.172.1.132/24 brd 10.172.1.255 scope global dynamic eth0
       valid_lft 82453sec preferred_lft 82453sec
    inet6 dd00:4191:d066:1:f816:3eff:fe51:6aef/64 scope global mngtmpaddr dynamic 
       valid_lft 82481sec preferred_lft 10481sec
    inet6 fe80::f816:3eff:fe51:6aef/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:02:c1:27 brd ff:ff:ff:ff:ff:ff
    inet6 dd00:4191:d066:1:f816:3eff:fe02:c127/64 scope global mngtmpaddr dynamic 
       valid_lft 82481sec preferred_lft 10481sec
    inet6 fe80::f816:3eff:fe02:c127/64 scope link 
       valid_lft forever preferred_lft forever
```
### Details
* If i configure macvlan on eth0 it works
  * it can ping 10.172.1.254 and 8.8.8.8
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'
```

* If i configure macvlan on eth1 if failed to connect to external network
  * it failed to ping 10.172.1.254 and 8.8.8.8
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth1",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'
```
  * network in the pod
  ```shell
  $ ip a
  1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
      inet 127.0.0.1/8 scope host lo
         valid_lft forever preferred_lft forever
      inet6 ::1/128 scope host 
         valid_lft forever preferred_lft forever
  2: net1@if3: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
      link/ether a6:62:7c:ca:a0:ff brd ff:ff:ff:ff:ff:ff link-netnsid 0
      inet 10.172.1.54/24 brd 10.172.1.255 scope global net1
         valid_lft forever preferred_lft forever
      inet6 dd00:4191:d066:1:a462:7cff:feca:a0ff/64 scope global mngtmpaddr dynamic 
         valid_lft 86365sec preferred_lft 14365sec
      inet6 fe80::a462:7cff:feca:a0ff/64 scope link 
         valid_lft forever preferred_lft forever
  14: eth0@if15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1350 qdisc noqueue state UP group default 
      link/ether 00:00:00:0b:13:db brd ff:ff:ff:ff:ff:ff link-netnsid 0
      inet 10.68.0.254/24 brd 10.68.0.255 scope global eth0
         valid_lft forever preferred_lft forever
      inet6 fe80::200:ff:fe0b:13db/64 scope link 
         valid_lft forever preferred_lft forever

  $ ip r
  default via 10.172.1.254 dev net1 
  10.68.0.0/24 dev eth0 proto kernel scope link src 10.68.0.254 
  10.96.0.0/12 via 10.68.0.1 dev eth0 
  10.172.1.0/24 dev net1 proto kernel scope link src 10.172.1.54
  ```

* arping
```shell
$ arping 10.172.1.82
Interface "net1" is not ARPable
```

### Additional info
* rp_filter = 0
* when i revert to eth0, it also didn't work and it worked after i reboot the host

**Comment by LiamLea** [comment]
* I found the problem.
  * the interface created in the pod has the NOARP flag. Then I enabled the ARP flag, it works perfectly.
  ```shell
  ip link set net1 arp on
  ```

* Is it a bug in the cni plugin?
  * pod annotations
  ```yaml
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "kube-ovn",
          "interface": "eth0",
          "ips": [
              "10.68.0.254"
          ],
          "mac": "00:00:00:7B:6A:24",
          "default": true,
          "dns": {},
          "gateway": [
              "10.68.0.1"
          ]
      },{
          "name": "kube-system/ovn-vpc-external-network",
          "interface": "net1",
          "ips": [
              "10.172.1.52"
          ],
          "mac": "1e:17:73:f3:d3:56",
          "dns": {}
      }]
  ```
