### ISSUE TITLE
Different Networks for Different Containers inside a Pod

### ISSUE THREAD

**Issue by Yuval-Ai** [k8snetworkplumbingwg/multus-cni#371]
Hi!
I need to connect two containers to two networks in the following way: 
```
+---------------------------------------------------------------------+
|                                                                     |
|   +------------------------+          +-----------------------+     |
|   |                        |          |                       |     |
|   |      container-a       |          |      container-b      |     |
|   |                        |          |                       |     |
|   |                        |          |                       |     |
|   |                        |          |                       |     |
|   |                        |          |                       |     |
|   |      +-----------+     |          |      +-----------+    |     |
|   |      | interface |     |          |      | interface |    |     |
|   |      +-----|-----+     |          |      +-----|-----+    |     |
|   +------------------------+          +-----------------------+     |
|                |                                   |                |
|                |                                   |                |
+------------------------------+ POD +--------------------------------+
                 |                                   |
                 |                                   |
         +-------+------+                     +------+-------+
         |              |                     |              |
         | my network 1 |                     | my network 2 |
         |              |                     |              |
         +--------------+                     +--------------+
```

In this scenario, the containers share the same Pod, but need to be exposed to different networks.

**Is there a way to achieve this kind of connection using Multus?** 

Thanks!

Example for my deployment's yaml file:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multus-2-containers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: multus-2-containers
      annotations:
       k8s.v1.cni.cncf.io/networks: my-net-1,my-net-2
    spec:
      containers:
      - name: container-a
        command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: ubuntu
        ports:
        - containerPort: 80

      - name: container-b
        command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: ubuntu
        ports:
        - containerPort: 80
```

Example for my-net-1 yaml:

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: my-net-1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp10s0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.10.10.0/24",
        "rangeStart": "10.10.10.1",
        "rangeEnd": "10.10.10.9"
      }
    }'

```

Example for my-net-2 yaml:

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: my-net-2
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp11s0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "20.20.20.0/24",
        "rangeStart": "20.20.20.1",
        "rangeEnd": "20.20.20.9"
      }
    }'

```
