### ISSUE TITLE
Picking the default network during Pod deployment

### ISSUE THREAD

**Issue by svallala** [k8snetworkplumbingwg/multus-cni#374]
Documents suggest that Multus will have a default network and every Pod will have an interface in that network. I have a use case where I have Calico and Flannel plugins. For one Pod I only want to have an interface from the Calico network and for the other pod, I would like to have an interface from Flannel network.

Can this be achieved using Multus? Currently, we are using CNI-Genie, which has the option to define the default-plugin, if a plugin is provided, then it will add an interface only from the plugin specified in the pod spec. Only if a plugin is not specified the default-plugin will be used.

Thanks

**Comment by dougbtv** [comment]
Hi @svallala sorry for the slow reply, we just discussed this during our maintainers meeting, you can attach multiple default networks using the `defaultNetworks` in the configuration. See some more detail here @

https://github.com/intel/multus-cni/blob/master/doc/configuration.md#multus-cni-configuration-reference

**Comment by svallala** [comment]
@dougbtv it's not clear going through the link. Given this requirement, can this be achieved using Multus

Need to create Pods with only one interface 

PodA - Interface using Flannel
PodB - Interface using Calico

Thanks

**Comment by Jc2k** [comment]
@svallala i suspect you are looking for the `v1.multus-cni.io/default-network` annotation.

You could do something like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: poda
  annotations:
    v1.multus-cni.io/default-network: flannel
---
apiVersion: v1
kind: Pod
metadata:
  name: podb
  annotations:
    v1.multus-cni.io/default-network: calico
```

To reference calico from the annotations (i think to reference it from a `k8s.v1.cni.cncf.io/networks`, so not sure if it applies to your use case or not) I had to create dummy NetworkAttachmentDefinition objects like this:

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: calico
spec: {}
```

I don't know when this is and isn't required but it seemed without that it couldn't see the calico conf in /etc/cni/net.d for my case. Make sure the name matches the name in the `.conf`/`.conflist`.

As part of testing I was able to change the primary network of a pod and not have any extra networks. But ultimately i was trying to set up a 2 interface pod, and I had extra issues. Currently calico does not work well if you try to make it a second network on a pod.
