### ISSUE TITLE
Multus interface issue with Host-device configuration

### ISSUE THREAD

**Issue by shailendra-singh93** [k8snetworkplumbingwg/multus-cni#557]
I have been trying to create a pod in openshift 4.2 cluster with extra multus interface of host-device.

Steps:
1. Created additional network attachment with the host-device CNI plug-in.
$ oc edit networks.operator.openshift.io cluster
Added section:

```
additionalNetworks: 
  - name: hostdevice
    type: Raw
    rawCNIConfig: '{
      "cniVersion": "0.3.1",
      "name": "hostdevice",
      "type": "host-device",
      "device": "eth0"
    }'
```

I can see hostdevice is created:
$ oc get network-attachment-definition
NAME         AGE
hostdevice   36m

Now i launch the pod with using below yaml file:

```
apiVersion: v1
kind: Pod
metadata:
  name: host-device-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: hostdevice
spec:
  containers:
  - name: host-device-pod-1
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools
  nodeSelector:
    kubernetes.io/hostname: worker4-0
```

When i list the pod, it stucks in containerCreation.
Please help, what i am missing
