### ISSUE TITLE
Multus does not raise a error on network annotation syntax error

### ISSUE THREAD

**Issue by s1061123** [k8snetworkplumbingwg/multus-cni#635]
**What happend**:
When the Pod network annotation is wrong (e.g. json syntax error), multus-cni does not raise error and proceed to build a pod without additional network interface

**What you expected to happen**:
In above case, multus-cni should raise a error and cancel to build a pod.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod with wrong json network annotation such as:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-runtimeconfig
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "centos-runtimeconfig-def",
              "ips": [ "10.1.1.104/24" ] 
    ]'
spec:
  containers:
  - name: centos-runtimeconfig
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true
```

**Anything else we need to know?**:
N/A

**Environment**:
snip because I'm working on fix.
