### ISSUE TITLE
Eth0 failing if adding specific netowrk attachment

### ISSUE THREAD

**Issue by elgamal2020** [k8snetworkplumbingwg/multus-cni#664]
**What happend**:

I am seeing a very strange behavior, seems a software bug , so when I add secondary network attachment mastered by specific interfaces “ens161 and ens162” , I lost the connectivity to eth0 of the pod , and it is shown as failed in the ip monitor 

I am seeing a very strange behavior, seems a software bug , so when I add secondary network attachment mastered by specific interfaces “ens161 and ens162” , I lost the connectivity to eth0 of the pod , and it is shown as failed in the ip monitor 

Environment : 

```
kubectl get nodes -o wide
NAME         STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
esmad0sl02   Ready    master   10d   v1.19.2   10.2.22.170   <none>        Ubuntu 20.04.1 LTS   5.4.0-42-generic   docker://19.3.13
esmad0sl03   Ready    master   10d   v1.19.2   10.2.22.171   <none>        Ubuntu 20.04.1 LTS   5.4.0-42-generic   docker://19.3.13
esmad0sl04   Ready    master   10d   v1.19.2   10.2.22.172   <none>        Ubuntu 20.04.1 LTS   5.4.0-42-generic   docker://19.3.13

```

interfaces on the host :
```

ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens161: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:a3:59:9b brd ff:ff:ff:ff:ff:ff
    inet 10.2.17.172/24 brd 10.2.17.255 scope global ens161
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea3:599b/64 scope link
       valid_lft forever preferred_lft forever
3: ens162: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:a3:92:0e brd ff:ff:ff:ff:ff:ff
    inet 10.2.26.172/24 brd 10.2.26.255 scope global ens162
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea3:920e/64 scope link
       valid_lft forever preferred_lft forever
4: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:a3:c3:cd brd ff:ff:ff:ff:ff:ff
    inet 10.2.22.172/24 brd 10.2.22.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea3:c3cd/64 scope link
       valid_lft forever preferred_lft forever
5: ens193: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:a3:6d:01 brd ff:ff:ff:ff:ff:ff
    inet 10.2.16.172/24 brd 10.2.16.255 scope global ens193
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea3:6d01/64 scope link
       valid_lft forever preferred_lft forever
6: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:a3:fa:b6 brd ff:ff:ff:ff:ff:ff
    inet 10.2.23.172/24 brd 10.2.23.255 scope global ens224
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea3:fab6/64 scope link
       valid_lft forever preferred_lft forever
7: ens225: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:a3:cd:68 brd ff:ff:ff:ff:ff:ff
    inet 10.2.24.172/24 brd 10.2.24.255 scope global ens225
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea3:cd68/64 scope link
       valid_lft forever preferred_lft forever
8: ens256: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:a3:ce:84 brd ff:ff:ff:ff:ff:ff
    inet 10.2.15.172/24 brd 10.2.15.255 scope global ens256
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea3:ce84/64 scope link
       valid_lft forever preferred_lft forever
9: ens257: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:a3:5d:0b brd ff:ff:ff:ff:ff:ff
    inet 10.2.25.172/24 brd 10.2.25.255 scope global ens257
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fea3:5d0b/64 scope link
       valid_lft forever preferred_lft forever


```
so what is quite odd that those two interfaces are shown as interface 1 and 2 while the Kuberentes NW for eth0 is interface 3 
Can the order be the issue ? , appreciating much your help and support 

Steps to reproduce. 
```

cat nad161 # Netowrk attachement Yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ens161
spec:
  config: '{ "cniVersion": "0.3.1", "plugins": [ { "type": "ipvlan", "mas

```
```
cat busy161 # pod Yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod161
  name: pod161
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name":
      "ens161","interface": "hamada","ips": ["10.2.17.181/24"]}
      ]'
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nti-node-type
            operator: In
            values:
            - tdb-tsp
  terminationGracePeriodSeconds: 0
  hostAliases:
  - hostnames:
    - ens161
    ip: 10.2.17.181
  containers:
  - name: busybox
    image: titan-ium-artifacts.netnumber.com/busybox:1.32.0
    args:
    - sleep
    - "1000000"
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
    env:
    - name: NNI_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: NNI_APP_PORT
      value: "80"
  restartPolicy: Always

```
```
kubectl apply -f nad161
networkattachmentdefinition.k8s.cni.cncf.io/ens161 created
kubectl apply -f busy161
pod/pod161 created
kubectl get pods -o wide
NAME     READY   STATUS    RESTARTS   AGE   IP              NODE         NOMINATED NODE   READINESS GATES
pod161   1/1     Running   0          37s   10.233.85.112   esmad0sl04   <none>           <none>

```
i```
nterfaces and routes on the pod 

```

kubectl exec pod161 -- ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if272: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether c2:a6:9b:33:2a:cb brd ff:ff:ff:ff:ff:ff
    inet 10.233.85.112/32 brd 10.233.85.112 scope global eth0
       valid_lft forever preferred_lft forever
4: hamada@if2: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue
    link/ether 00:50:56:a3:59:9b brd ff:ff:ff:ff:ff:ff
    inet 10.2.17.181/24 brd 10.2.17.255 scope global hamada
       valid_lft forever preferred_lft forever
kubectl exec pod161 -- ip r
default via 169.254.1.1 dev eth0
10.2.17.0/24 dev hamada scope link  src 10.2.17.181
169.254.1.1 dev eth0 scope link
```
```

```
then run ip monitor in the hosting node esmad0sl04   
```

ip monitor all | grep FAIL
[NEIGH]10.233.85.95 dev califac420b0ff3  FAILED
[NEIGH]10.233.85.95 dev califac420b0ff3  FAILED
[NEIGH]10.233.85.95 dev califac420b0ff3  FAILED
```

`Also  the ping shows it go through ens161 while it should go through ens192
```
`ping 10.233.85.112
PING 10.233.85.112 (10.233.85.112) 56(84) bytes of data.
From 10.2.17.172 icmp_seq=1 Destination Host Unreachable
```

If I disable the interface ens161, the ping turns successful

 

I tried to change the routes, applying default routes, deleting the routes from the host but nothing works 
I didn’t succeed to change the order of interface numbering and I don’t know on what it depends. 

I am really appreciating much your help. 

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
9b13777edc63

- Kubernetes version (use `kubectl version`):
- 1.19.2
- Primary CNI for Kubernetes cluster:
Calico 
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

```
