### ISSUE TITLE
Multus "global namespaces" does not work with JSON format annotations

### ISSUE THREAD

**Issue by dougbtv** [k8snetworkplumbingwg/multus-cni#705]
Steps to Reproduce:
1. Create a net-attach-def in the openshift-multus namespace with:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens4",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'
```

2. Create a new project, create a pod in it with a JSON selection annotation, e.g.:

```
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"name": "openshift-multus/macvlan-conf"}]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
```

Actual results: The pod eventually errors out with:

```
  Warning  FailedCreatePodSandBox  4m59s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_samplepod_dougtest_7e745545-2af4-4580-a048-ae566e8d991b_0(8e4f62ef30dafa54013399e62ea08391d9edf9a39e89ce0b483da0cf0118212f): error adding pod dougtest_samplepod to CNI network "multus-cni-network": Multus: [dougtest/samplepod]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: cannot find a network-attachment-definition (openshift-multus/macvlan-conf) in namespace (dougtest): invalid resource name "openshift-multus/macvlan-conf": [may not contain '/']

```

Expected results: The

Additional info: Notably, the pod successfully spins up without using the JSON annotation, so for example, this spec currently works:

```
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: openshift-multus/macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
```
