### ISSUE TITLE
Unable to use network-attachment-definitions at Cluster scope

### ISSUE THREAD

**Issue by barryboubakar** [k8snetworkplumbingwg/multus-cni#713]
**What happend**:
I am trying to set the network-attachment-definitions available for all the cluster and not only for a namespace.

To do so, I have changed the CustomResourceDefinition in the `multus-daemonset.yml` as follow (Scope is now `Cluster` and not `Namespaced`):

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  scope: Cluster
  names:
    plural: network-attachment-definitions
    singular: network-attachment-definition
    kind: NetworkAttachmentDefinition
    shortNames:
    - net-attach-def
[...]
```

Then I have created the network-attachment-definition with the following yaml:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'
```

I can now list this network-attachment-definition everywhere on my cluster:

```
# kubectl get net-attach-def -n default
NAME           AGE
macvlan-conf   17h
# kubectl get net-attach-def -n nad30
NAME           AGE
macvlan-conf   17h
```

Then, I create a pod using this network-attachment-definition:

```
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
```

Here is the issue, no in which namespace I deploy this to (namespace default or nad30) the creation failed with the following error:

```
Warning  FailedCreatePodSandBox  14s                 kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ecea10052603a3da2b66cc8220fa9c2fa2424a0d1b76a572fc09077314efba54" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_default" network: Multus: [default/samplepod]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: cannot find a network-attachment-definition (macvlan-conf) in namespace (default): the server could not find the requested resource (get network-attachment-definitions.k8s.cni.cncf.io macvlan-conf)
Warning  NoNetworkFound          14s                 multus             cannot find a network-attachment-definition (macvlan-conf) in namespace (default): the server could not find the requested resource (get network-attachment-definitions.k8s.cni.cncf.io macvlan-conf)
```

**What you expected to happen**:

I expect the pod to be attached to the network I defined since the NAD is available in any namespace.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps I describe previously.

**Environment**:

- Multus version 
  ghcr.io/k8snetworkplumbingwg/multus-cni:stable

- Kubernetes version (use `kubectl version`): 1.18.10
  
- Primary CNI for Kubernetes cluster: Canal/Flanel 
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- File of '/etc/cni/net.d/' 
  00-multus.conf
  10-canal.conflist 
   calico-kubeconfig
  
- File of '/etc/cni/multus/net.d'
   None 

Thanks.
