### ISSUE TITLE
Error adding container to network "cbr0": must be called as chained plugin 

### ISSUE THREAD

**Issue by MaxThom** [k8snetworkplumbingwg/multus-cni#714]
Hey,
I have installed MultusCNI in a K3S cluster. Everything was working fine, until this morning (a week after working fine).
Each time I add a new pod, I get this message:
```
Warning  FailedCreatePodSandBox  3s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed ││  to setup network for sandbox "6c9215c6217bf47705e90719cb264e419c8bf0ac52f1c2feccb4ad496e015abd": [max-dev/mc-void:cbr0]: error a ││ dding container to network "cbr0": must be called as chained plugin 
```

I have modified the daemonset to point to the right folders for binaries and configs.
I added ```macvlan``` binary to the binaries.
Everything was working fine, I was able to udp multicast from outside to inside the cluster.

Now, each time I create a pod, even without Network Attachment, I get the error message.
Any idea?

Thank you :)

<details>
  <summary>DaemonSet</summary>

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: multus
      containers:
      - name: kube-multus
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:stable
        command: ["/entrypoint.sh"]
        args:
        - "--multus-conf-file=auto"
        - "--cni-version=0.3.1"
        # Add this line
        - "--multus-kubeconfig-file-host=/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig"
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: multus-cfg
          mountPath: /tmp/multus-conf
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cni
          hostPath:
            path: /var/lib/rancher/k3s/agent/etc/cni/net.d #/etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /var/lib/rancher/k3s/data/current/bin #/opt/cni/bin
        - name: multus-cfg
          configMap:
            name: multus-cni-config
            items:
            - key: cni-conf.json
              path: 70-multus.conf
```
</details>

<details>
  <summary>Net-Attach</summary>

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: eno1-mc
  namespace: max-dev
spec:
  config: '{
            "cniVersion": "0.3.1",
            "type": "macvlan",
            "master": "eno1",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "10.10.8.0/24",
                         "rangeStart": "10.10.8.15",
                         "rangeEnd": "10.10.8.251"
                    } ]
                ]
            }
        }'
```
</details>

<details>
  <summary>Flannel</summary>

This is the ```10-flannel.confilist```

```json
{
  "name":"cbr0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "type":"flannel",
      "delegate":{
        "hairpinMode":true,
        "forceAddress":true,
        "isDefaultGateway":true
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
```
</details>
