### ISSUE TITLE
Conf files in Multiple Nodes

### ISSUE THREAD

**Issue by MaxThom** [k8snetworkplumbingwg/multus-cni#716]
Hey,
I have installed MultusCNI in a K3S cluster. Everything working fine with the spec inside the yaml. 

To address the problem of multiple node, I want to use the file solution in the HowToUse and the YAML just reference that file. I tried adding the spec file inside ````/var/lib/rancher/k3s/agent/etc/cni/net.d/```` and ```/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d```, but I still have the error that Multus cannot find the configuration file when I create a pod. Ive also tried to ssh into the pod of the daemonset and manually add the config file in etc/cni/multus/net.d. Same error. I tried to mount another folder with my configurations file (macvlan2.conf) inside to /etc/cni/multus/net.d. Same error.

I also tried to add the config in the delegate array of ```00-multus.conf```, but that made the network interface added in every pod created.

Each time I add a new pod, I get this message:
```
Multu ││ s: [max-dev/mc-file2]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for p ││ od: GetNetworkDelegates: failed getting the delegate: GetCNIConfig: err in GetCNIConfigFromFile: No networks found in /etc/cni/multus/net.d                     
```

I have modified the daemonset to point to the right folders for binaries and configs. 

Any idea?

Thank you :)

<details>
  <summary>DaemonSet</summary>

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: multus
      containers:
      - name: kube-multus
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:stable
        command: ["/entrypoint.sh"]
        args:
        - "--multus-conf-file=auto"
        - "--cni-version=0.3.1"
        # Add this line
        - "--multus-kubeconfig-file-host=/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig"
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: multus-cfg
          mountPath: /tmp/multus-conf
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cni
          hostPath:
            path: /var/lib/rancher/k3s/agent/etc/cni/net.d #/etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /var/lib/rancher/k3s/data/current/bin #/opt/cni/bin
        - name: multus-cfg
          configMap:
            name: multus-cni-config
            items:
            - key: cni-conf.json
              path: 70-multus.conf
```
</details>

<details>
  <summary>Net-Attach</summary>

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-mc-conf
  namespace: max-dev
```
</details>

<details>
  <summary>Pod</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mc-file
  namespace: max-dev
  annotations:
    k8s.v1.cni.cncf.io/networks: max-dev/macvlan-mc-conf@eno1
spec:
  containers:
  - name: example-multicast-pod
    command: ["iperf", "-s", "-u", "-B", "224.0.67.67%eno1", "-i", "1"]
    image: bagoulla/iperf:2.0
```
</details>

<details>
  <summary>macvlan-mc-conf</summary>

```json
{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "name": "macvlan-mc-conf",
      "master": "eno1",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "10.10.8.0/24",
              "rangeStart": "10.10.8.15",
              "rangeEnd": "10.10.8.251"
            }
          ]
        ]
      }
    }
```
</details>

<details>
  <summary>Flannel</summary>

This is the ```10-flannel.conflist```

```json
{
  "name":"cbr0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "type":"flannel",
      "delegate":{
        "hairpinMode":true,
        "forceAddress":true,
        "isDefaultGateway":true
      }
    },
    {
      "type":"portmap",
      "capabilities":{
        "portMappings":true
      }
    }
  ]
}
```
</details>

<details>
<summary>Multis Config</summary>

```json
{
  "cniVersion": "0.3.1",
  "name": "multus-cni-network",
  "type": "multus",
  "capabilities": {
    "portMappings": true
  },
  "kubeconfig": "/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig",
  "delegates": [
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "forceAddress": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  ]
}
```

</details>
