### ISSUE TITLE
Unable to egress out of my pod with multiple network interfaces attached

### ISSUE THREAD

**Issue by iKarthik** [k8snetworkplumbingwg/multus-cni#733]
**What happend**:
I have installed multus cni on top of my EKS cluster which is running VPC CNI as primary. I mostly followed the instructions from https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-multus-cni/.

**What you expected to happen**:
I expected to be able to egress out from my pod (in public subnet) to the word via eth0 and net1, but i was unable to do so. Both ping and curl seems to fail 

**How to reproduce it (as minimally and precisely as possible)**:
Following the instructions from the doc referred about, i have everything multus related up and running in my cluster. Two network interfaces show up as expected. Here is my NetworkAttachmentDefinition.  I obtained the gateway ip, but doing route -n on the node, please let me know if this is invalid. I got the subnet information from my subnet CIDR block

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-conf-1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth1",
      "mode": "l3",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.2.0/23",
        "rangeStart": "192.168.3.10",
        "rangeEnd": "192.168.3.100",
        "gateway": "192.168.2.1"
      }
    }'


```
Here is a simple app deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
    owner: kay
    env: dev
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: bridge-conf-1
      labels:
        app: sample-app
        owner: kay
        env: dev
    spec:
      containers:
        - name: network-multitool
          image: praqma/network-multitool:latest

```

**Anything else we need to know?**:

**Environment**:
EKS

- Multus version 
  image path and image ID (from 'docker images')
- K8s version: 1.20
- Kubectl: Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/arm64"}
- 00-multus.conf
`   { "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "capabilities": {"portMappings": true}, "logLevel": "error", "logFile": "/var/log/aws-routed-eni/multus.log", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "cniVersion": "0.3.1", "name": "aws-cni", "plugins": [ { "name": "aws-cni", "type": "aws-cni", "vethPrefix": "eni", "mtu": "9001", "pluginLogFile": "/var/log/aws-routed-eni/plugin.log", "pluginLogLevel": "DEBUG" }, { "type": "portmap", "capabilities": {"portMappings": true}, "snat": true } ] } ] }`

- Primary CNI for Kubernetes cluster: AWS VPC CNI
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
```
  apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"bridge-conf-1","namespace":"kube-system"},"spec":{"config":"{ \"cniVersion\": \"0.3.0\", \"type\": \"ipvlan\", \"master\": \"eth1\", \"mode\": \"l3\", \"ipam\": { \"type\": \"host-local\", \"subnet\": \"192.168.2.0/23\", \"rangeStart\": \"192.168.3.10\", \"rangeEnd\": \"192.168.3.100\", \"gateway\": \"192.168.2.1\" } }"}}
    creationTimestamp: "2021-10-11T20:41:02Z"
    generation: 1
    name: bridge-conf-1
    namespace: kube-system
    resourceVersion: "30318"
    uid: 49a2d6fd-549d-414d-b174-65b71f1d7629
  spec:
    config: '{ "cniVersion": "0.3.0", "type": "ipvlan", "master": "eth1", "mode":
      "l3", "ipam": { "type": "host-local", "subnet": "192.168.2.0/23", "rangeStart":
      "192.168.3.10", "rangeEnd": "192.168.3.100", "gateway": "192.168.2.1" } }'
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```
- ip -d address from within the pod
```

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 minmtu 0 maxmtu 0 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default
    link/ether ba:e9:ca:be:14:3f brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0 minmtu 68 maxmtu 65535
    veth numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet 192.168.2.115/32 scope global eth0
       valid_lft forever preferred_lft forever
4: net1: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 9001 qdisc noqueue state UNKNOWN group default
    link/ether 12:a2:2f:0d:f3:fd brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535
    ipvlan  mode l3 bridge numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet 192.168.3.15/23 brd 192.168.3.255 scope global net1
       valid_lft forever preferred_lft forever
```

It looks like am missing something here, can someone help?

Thanks
Kay
