### ISSUE TITLE
How to start new pod with multus using macvlan type? Error in starting pods.

### ISSUE THREAD

**Issue by ionutnechita** [k8snetworkplumbingwg/multus-cni#739]
Yaml deployment: https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/release-3.7/images/multus-daemonset.yml

Error: kube-system/pod-case-02:macvlan-conf-1]: error adding container to network "macvlan-conf-1": failed to find plugin "macvlan" in path [/opt/cni/bin /opt/cni/bin]

**_How to enable macvlan plugin in multus pods?_**

```
Events:                                                                                                                                                             │
│   Type     Reason                  Age   From               Message                                                                                                 │
│   ----     ------                  ----  ----               -------                                                                                                 │
│   Normal   Scheduled               8s    default-scheduler  Successfully assigned kube-system/pod-case-02 to kind-worker                                            │
│   Normal   AddedInterface          7s    multus             Add eth0 [10.244.4.200/24]                                                                              │
│   Warning  FailedCreatePodSandBox  7s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "deb │
│ b8cec7c201f8a0a905da066380fbd7772679dd13fd8543136e54eeff99a47": [kube-system/pod-case-02:macvlan-conf-1]: error adding container to network "macvlan-conf-1": faile │
│ d to find plugin "macvlan" in path [/opt/cni/bin /opt/cni/bin]  
```

```
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
  namespace: kube-system
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "eth1",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "10.10.0.0/16",
                         "rangeStart": "10.10.1.20",
                         "rangeEnd": "10.10.3.50",
                         "gateway": "10.10.0.254"
                    } ]
                ]
            }
        }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ptp-conf-1
  namespace: kube-system
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "ptp",
            "master": "eth2",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "10.10.0.0/16",
                         "rangeStart": "10.10.6.20",
                         "rangeEnd": "10.10.8.50",
                         "gateway": "10.10.5.254"
                    } ]
                ]
            }
        }'
```
```
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-case-02
  namespace: kube-system
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name" : "macvlan-conf-1",
              "namespace": "kube-system" }
    ]'
spec:
  containers:
  - name: pod-case-02
    image: docker.io/ionutnechita/alpine:multus
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]

```
