### ISSUE TITLE
Ignore default routes from dhcp

### ISSUE THREAD

**Issue by resetsa** [k8snetworkplumbingwg/multus-cni#748]
Hi all!
Help me. Please describe me, how i can ignore default routes from dhcp server.
At this moment i'm have 2 default routes in pod.
From dhcp + k8s cluster default.
```
/ # ip route 
default via 192.168.113.1 dev vlan10
default via 169.254.1.1 dev eth0
169.254.1.1 dev eth0 scope link
192.168.113.0/28 dev vlan10 scope link  src 192.168.113.7
```

pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: ns-test
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
         { "name":"vlan10", "interface":"vlan10","mac":"B2:7F:B2:F6:14:5A" }
      ]
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: powersa.io/vlan10
              operator: Exists
  containers:
  - image: alpine:3.12.8
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
    resources:
      limits:
        cpu: "0.2"
        memory: "128Mi"
      requests:
        cpu: "0.1"
        memory: "64Mi"
  restartPolicy: Always
```

vlan10.yaml
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan10
  namespace: ns-test
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "vlan10",
      "ipam": {
        "type": "dhcp"
      }
    }'
```
