### ISSUE TITLE
Dynamic VLAN configuration (IEEE 802.1ad)

### ISSUE THREAD

**Issue by raballew** [k8snetworkplumbingwg/multus-cni#751]
**Context**

I am running several k8s clusters on bare metal whose worker nodes are attached to several different networks. All workers are configured identically. One of the interfaces (eno1) is attached to a static outer VLAN (ID 2) that is not routed. In the outer VLAN there are embedded devices that should communicate with pods running on k8s. The challenge now is that those embedded devices require **dynamically** VLAN tagged ethernet frames (dynamically VLAN tagged means that the VLAN tag is defined in the pod manifest definition e.g. the pod decided which embedded device to talk to) to properly communicate with the pods running on k8s. There is no way I can disable this setting. Hence the embedded devices and pods use an inner VLAN to communicate which nested in the outer VLAN. The standard that offers those capabilities is `IEEE 802.1ad`. All switches in my network support this standard.

What was a challenge before, becomes a problem now. Since there are multiple inner VLANs and potentially multiple outer VLANs in scaled setups to keep broadcast domains small, I would need to create a large amount of interfaces upfront. If I would use 5 different outer VLANs and 20 different inner VLANs this would result in 100 interfaces that need to be created upfront on all nodes and it gets worse in bigger setups.

This is what I would have done on node level for 2 outer and 3 inner VLANs.

```bash
# outer vlan 2
ip link add name eno1.2 link eno1 type vlan id 2 ### add vlan2 to eno1
ip link add name eno1.2.10 link eno1.2 type vlan id 10 ### add vlan10 to vlan2
ip link add name eno1.2.11 link eno1.2 type vlan id 11 ### add vlan11 to vlan2
ip link add name eno1.2.12 link eno1.2 type vlan id 12 ### add vlan12 to vlan2

# outer vlan 3
ip link add name eno1.3 link eno1 type vlan id 2 ### add vlan3 to eno1
ip link add name eno1.3.10 link eno1.3 type vlan id 10 ### add vlan10 to vlan3
ip link add name eno1.3.11 link eno1.3 type vlan id 11 ### add vlan11 to vlan3
ip link add name eno1.3.12 link eno1.3 type vlan id 12 ### add vlan12 to vlan3

# outer vlan x
...
```

Also it must be possible to attach multiple pods to the same inner VLAN interface. So that a potential NetworkAttachmentDefinition would look like this:

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno1.2.10",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp"
      }
    }'
```

**Question**

Is there a way to dynamically create interfaces with nested VLAN configurations according to `IEEE 802.1ad` standard using Multus?
