### ISSUE TITLE
inconsistent CNI results reported on the CNI cache

### ISSUE THREAD

**Issue by maiqueb** [k8snetworkplumbingwg/multus-cni#760]
**What happened**:
Creating a pod having the `default-route` `NetworkSelectionElement` parameter set results in inconsistent CNI results, depending on the `NetworkAttachmentDefinition` referred to by the selection element.

When the NAD **does NOT** feature gateway information, the CNI results fail to report the routes on it; when the NAD **features** route information, the routes are reported in the CNI results.

Despite this, in both NAD configuration, the default route is updated, and the gateway set.

**What you expected to happen**:
The CNI results should feature the gateway information independently of the route information presence in the POD's network selection elements.

**How to reproduce it (as minimally and precisely as possible)**:
- Provision the [e2e tests default route example](https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/e2e/default-route1.yml)
- check the pod's routes: 
```bash
kubectl exec default-route-worker1 -- ip r
default via 10.1.1.254 dev net1 
10.1.1.0/24 dev net1 proto kernel scope link src 10.1.1.21 
10.244.1.0/24 via 10.244.1.1 dev eth0 src 10.244.1.2 
10.244.1.1 dev eth0 scope link src 10.244.1.2 
```
- identify in which node is the `default-route-worker1` pod running
```bash
kubectl get pods default-route-worker1 -ogo-template="{{ .spec.nodeName }}"
kind-worker
```
- check the CNI cached results
```bash
podman exec kind-worker cat /var/lib/cni/multus/results/default-route-config-1af4295d98f9aee87420accb459e40350f5a716a1f017ed02bc7877119c2e8d6-net1 | jq
{
  "kind": "cniCacheV1",
  "containerId": "1af4295d98f9aee87420accb459e40350f5a716a1f017ed02bc7877119c2e8d6",
  "config": "eyJjbmlWZXJzaW9uIjoiMC4zLjEiLCJuYW1lIjoiZGVmYXVsdC1yb3V0ZS1jb25maWciLCJwbHVnaW5zIjpbeyJpcGFtIjp7InR5cGUiOiJzdGF0aWMifSwibWFzdGVyIjoiZXRoMSIsIm1vZGUiOiJicmlkZ2UiLCJ0eXBlIjoibWFjdmxhbiJ9XX0=",
  "ifName": "net1",
  "networkName": "default-route-config",
  "cniArgs": [
    [
      "IgnoreUnknown",
      "true"
    ],
    [
      "K8S_POD_NAMESPACE",
      "default"
    ],
    [
      "K8S_POD_NAME",
      "default-route-worker1"
    ],
    [
      "K8S_POD_INFRA_CONTAINER_ID",
      "1af4295d98f9aee87420accb459e40350f5a716a1f017ed02bc7877119c2e8d6"
    ],
    [
      "K8S_POD_UID",
      ""
    ],
    [
      "IP",
      "10.1.1.21/24"
    ]
  ],
  "capabilityArgs": {
    "ips": [
      "10.1.1.21/24"
    ]
  },
  "result": {
    "cniVersion": "0.3.1",
    "dns": {},
    "interfaces": [
      {
        "mac": "fe:19:09:1f:62:f1",
        "name": "net1",
        "sandbox": "/var/run/netns/cni-71210e26-47b4-14bc-408f-5d20844799b2"
      }
    ],
    "ips": [
      {
        "address": "10.1.1.21/24",
        "interface": 0,
        "version": "4"
      }
    ]
  }
}
```

The route information will **not** be present.

**Anything else we need to know?**:
If the following NAD is used instead:
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: default-route-config
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "macvlan",
                    "master": "eth1",
                    "mode": "bridge",
                    "ipam": {
                        "type": "static",
                        "routes": [
                          {
                            "dst": "0.0.0.0/0",
                            "gw": "10.1.1.254"
                          }
                        ]
                    }
                } ]
        }'
```

The CNI cached results **will feature** the route information:
```bash
podman exec kind-worker cat /var/lib/cni/multus/results/default-route-config-aa27b1dd9cecae1b400305cda6f33f206b6a63eb1239c90633728fdff4b036cc-net1 | jq 
{
  "kind": "cniCacheV1",
  "containerId": "aa27b1dd9cecae1b400305cda6f33f206b6a63eb1239c90633728fdff4b036cc",
  "config": "eyJjbmlWZXJzaW9uIjoiMC4zLjEiLCJuYW1lIjoiZGVmYXVsdC1yb3V0ZS1jb25maWciLCJwbHVnaW5zIjpbeyJpcGFtIjp7InJvdXRlcyI6W3siZHN0IjoiMC4wLjAuMC8wIiwiZ3ciOiIxMC4xLjEuMjU0In1dLCJ0eXBlIjoic3RhdGljIn0sIm1hc3RlciI6ImV0aDEiLCJtb2RlIjoiYnJpZGdlIiwidHlwZSI6Im1hY3ZsYW4ifV19",
  "ifName": "net1",
  "networkName": "default-route-config",
  "cniArgs": [
    [
      "IgnoreUnknown",
      "true"
    ],
    [
      "K8S_POD_NAMESPACE",
      "default"
    ],
    [
      "K8S_POD_NAME",
      "default-route-worker2"
    ],
    [
      "K8S_POD_INFRA_CONTAINER_ID",
      "aa27b1dd9cecae1b400305cda6f33f206b6a63eb1239c90633728fdff4b036cc"
    ],
    [
      "K8S_POD_UID",
      ""
    ],
    [
      "IP",
      "10.1.1.22/24"
    ]
  ],
  "capabilityArgs": {
    "ips": [
      "10.1.1.22/24"
    ]
  },
  "result": {
    "cniVersion": "0.3.1",
    "dns": {},
    "interfaces": [
      {
        "mac": "ee:55:20:7e:ca:5b",
        "name": "net1",
        "sandbox": "/var/run/netns/cni-208e7c39-29b4-87a9-420e-71b0df9c6af0"
      }
    ],
    "ips": [
      {
        "address": "10.1.1.22/24",
        "interface": 0,
        "version": "4"
      }
    ],
    "routes": [
      {
        "dst": "0.0.0.0/0",
        "gw": "10.1.1.254"
      }
    ]
  }
}
```

**Environment**:

- Multus version: 3.8
