### ISSUE TITLE
NetworkAttachmentDefinition config as yaml instead of json

### ISSUE THREAD

**Issue by Sispheor** [k8snetworkplumbingwg/multus-cni#765]
Hello there 👋,

I'm installing OCS operator on Openshift 4.9. Just discover that now this plugin was required.

I just wanted to know if a full yaml config was supported for the NetworkAttachmentDefinition CR or will be supported?

In the documentation I can read that we pass a json config into the yaml description like this:
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ocs-public-cluster
  namespace: openshift-storage
spec:
  config: '{
  	"cniVersion": "0.3.1",
  	"type": "macvlan",
  	"master": "ens2",
  	"mode": "bridge",
  	"ipam": {
    	    "type": "whereabouts",
    	    "range": "192.168.1.0/24"
  	}
  }'
```

Just wanted to know if the current implementation was supporting a full yaml description like this:
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ocs-public-cluster
  namespace: openshift-storage
spec:
  config:
    cniVersion: 0.3.1
    type: macvlan
    master: ens2
    mode: bridge
    ipam:
      type: whereabouts
      range: 192.168.1.0/24
```

It's just that when wrapping all of the config with an automation engine like Ansible it become touchy to insert json into yaml and keep double quote and stuff 😅.

Thanks by advance for your time.
