### ISSUE TITLE
How to allow all incoming routes to a static macvlan ip?

### ISSUE THREAD

**Issue by RandomGHUser** [k8snetworkplumbingwg/multus-cni#793]
I can currently make my static IP address accessible from my 192.x VLANS with this config:
```yaml
spec:
  config: '{
  "cniVersion": "0.3.0",
  "type": "macvlan",
  "master": "vlan66-dmz",
  "ipam": {
  "type": "static",
  "addresses": [ 
    {
      "address": "192.168.66.27/24", 
      "gateway": "192.168.66.1" 
    }
  ],
  "routes": [ 
    {
      "dst": "192.0.0.0/8",
      "gw": "192.168.66.1" 
    }
  ]
  }
  }'
```

I would like to make the IP address accessible from any incoming route.   I am unsure how to do this.  If I change the routes dst value to "0.0.0.0/0", I cannot access the ip from any of my networks.   I'm sure this is a simple issue, and any help is appreciated.

**Comment by RandomGHUser** [comment]
I was able to allow all incoming routes this way:
```yaml
 "routes": [ 
    {
      "dst": "0.0.0.0/1",
      "gw": "192.168.66.1" 
    },
  {
      "dst": "128.0.0.0/1",
      "gw": "192.168.66.1" 
    }
  ]
```
Not sure if this is a good practice or not, but seems to work proper.
