### ISSUE TITLE
How to keep Pod network route when specifying a default route?

### ISSUE THREAD

**Issue by stephan2012** [k8snetworkplumbingwg/multus-cni#847]
Currently, I am struggling with a Multus setup that adds a second interface and changes the default route to it:

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "macvlan",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "192.168.8.0/22",
              "rangeStart": "192.168.8.248",
              "rangeEnd": "192.168.8.254",
              "gateway": "192.168.8.1"
            }
          ]
        ],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    }'
```

Excerpt from the Deployment:

```yaml
spec:
  template:
    metadata:
      annotations:
        # k8s.v1.cni.cncf.io/networks: macvlan-conf
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "macvlan-conf",
            "default-route": ["192.168.8.1"]
          }]
```

The configuration works, but Pod network connectivity has gone.

The [docs](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/how-to-use.md#specifying-a-default-route-for-a-specific-attachment) mention the impact of changing the default route on the Pod network connectivity. However, it seems that all it needs is an additional route to the Pod network route:

```bash
root@shell-587b5459c-lkpwp:/# ip r
default via 192.168.8.1 dev net1 
169.254.1.1 dev eth0 scope link 
192.168.8.0/22 dev net1 proto kernel scope link src 192.168.8.249 
```

How can I make Multus add it? Any attempt to specify it result in an error because Multus always adds `dev net1`.

**Comment by dougbtv** [comment]
I think you could use route-override-cni to add a static route: https://github.com/openshift/route-override-cni

Please reopen if this didn't quite do the trick. Thanks

**Comment by maxpain** [comment]
The problem is that Calico uses 169.254.1.1 as a default gateway. Can we override this behavior? I think in the case of multiple interfaces Calico should add `192.168.8.0/22` route instead of `169.254.1.1` and all traffic to the cluster network will be routed via the calico interface.

**Comment by stephan2012** [comment]
> I think you could use route-override-cni to add a static route: https://github.com/openshift/route-override-cni
> Please reopen if this didn't quite do the trick. Thanks

No, [route-override-cni](https://github.com/openshift/route-override-cni) does not work. I can configure routes additional routes through it, but all routes with gateway 169.254.1.1 seem to end up in a noop. Also, setting a host route to the worker node does not work.

Manually adding the routes (given that the `NET_ADMIN` capability has been added to the Pod) makes Pod network connectivity (and livenessProbes) work, so it does not seem to be a general issue with the Linux network stack:

```
# ip route add 172.30.0.0/16 via 169.254.1.1   # Pod network is 172.30.0.0/16
# ping 172.30.28.148
PING 172.30.28.148 (172.30.28.148) 56(84) bytes of data.
64 bytes from 172.30.28.148: icmp_seq=1 ttl=62 time=0.555 ms
64 bytes from 172.30.28.148: icmp_seq=2 ttl=62 time=0.492 ms
^C
--- 172.30.28.148 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1012ms
rtt min/avg/max/mdev = 0.492/0.523/0.555/0.031 ms
```

From the config below, only the route `100.67.0.0/16` is available in the Pod:

```json
{
  "cniVersion": "0.4.0",
  "name": "macvlan",
  "plugins": [
    {
      "ipam": {
        "addresses": [
          {
            "address": "192.168.8.72/22",
            "gateway": "192.168.8.1"
          }
        ],
        "routes": [],
        "type": "static"
      },
      "mode": "bridge",
      "type": "macvlan"
    },
    {
      "addroutes": [
        {
          "dst": "192.168.8.56/32",
          "gw": "169.254.1.1"
        },
        {
          "dst": "100.67.0.0/16",
          "gw": "192.168.8.1"
        },
        {
          "dst": "172.30.0.0/16",
          "gw": "169.254.1.1"
        }
      ],
      "type": "route-override"
    }
  ]
}
```

```bash
$ ip r
default via 192.168.8.1 dev net1 
100.67.0.0/16 via 192.168.8.1 dev net1 
169.254.1.1 dev eth0 scope link 
192.168.8.0/22 dev net1 proto kernel scope link src 192.168.8.72 
```

**Comment by maxpain** [comment]
Any updates?

**Comment by maxpain** [comment]
@dougbtv could you please reopen this issue?

**Comment by maxpain** [comment]
I have the same problem. My primary cni is cilium, and the secondary is macvlan with default route (0.0.0.0).
I need to access my primary cluster network via the cilium interface. How to add the route (for example 10.0.0.0/8) to cilium interface?

**Comment by stephan2012** [comment]
For my specific use-case it looks like I got my application working by configuring [Source-based routing](https://www.cni.dev/plugins/v0.8/meta/sbr/), so response packets take the same network interface that the connection entered the system. Not sure if I should consider it a solution or a workaround.

**Comment by s1061123** [comment]
So first, multus cni is just a meta plugin and multus expects that delegating CNI handles for that primary. So you may ask CNI provider to change the route (not only add, also delete). To force to change specific route, [cni-route-override](https://github.com/redhat-nfvpe/cni-route-override) could help you to do that, but it just 'forces to change routing table', so it may affect to parent CNI plugin. So the best case should to add support routing by delegating CNI plugin itself.

Regarding sbr plugin, I am not good at sbr so hope that someone else will answer it.

**Comment by yagosys** [comment]
there is a way you might try.
1. change calico IPAM from calico-ipam to host-local. as calico IPAM does not support "routes key" word
2. after change to host-local , add specfic route entry in host-local 
3. if there is specifc router entry exist, calico will not install default route.  otherise, calico will install default route.
here is my snip of calico cni config //10-calico.conflist 
`      "ipam": {
          "type": "host-local",
          "subnet": "usePodCidr",
          "routes": [
            { "dst": "1.2.3.4/32", "gw": "127.0.0.1" }
          ]`

here is the route table of my POD.
`ubuntu@ip-10-0-1-100:/etc/cni/net.d$ kubectl exec -it po/multitool-deployment-6d7848d458-t9jzv -- sh
/ # ip r
default via 10.244.0.1 dev net1
1.2.3.4 via 169.254.1.1 dev eth0
10.244.0.0/24 dev net1 proto kernel scope link src 10.244.0.62
10.244.0.0/16 via 10.244.0.1 dev net1
169.254.1.1 dev eth0 scope link`

**Comment by adrienthebo** [comment]
I'm running into this problem as well; I'm using k3s with flannel; I need to route outbound traffic through an additional interface while maintaining connectivity to the overlay network. Using a default route adds an additional default route but does not replace the default route.

**Without route-override*:*

```json
{
  "cniVersion": "0.3.1",
  "name": "macvlan-1129",
  "plugins": [
    {
      "type": "macvlan",
      "master": "enp4s0f4u1.1129",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.192.129.0/24",
        "rangeStart": "10.192.129.200",
        "rangeEnd": "10.192.129.207",
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ],
        "gateway": "10.192.129.1"
      }
    }
  ]
}
```

```
default via 10.192.129.1 dev net1
default via 10.42.0.1 dev eth0
10.42.0.0/24 dev eth0 scope link  src 10.42.0.182
10.42.0.0/16 via 10.42.0.1 dev eth0
10.192.129.0/24 dev net1 scope link  src 10.192.129.200
```

**Using route-override:**

```json
{
  "cniVersion": "0.3.1",
  "name": "macvlan-1129",
  "plugins": [
    {
      "type": "macvlan",
      "master": "enp4s0f4u1.1129",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.192.129.0/24",
        "rangeStart": "10.192.129.200",
        "rangeEnd": "10.192.129.207",
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ],
        "gateway": "10.192.129.1"
      }
    },
    {
      "type": "route-override",
      "flushgateway": true
    }
  ]
}
```

```
default via 10.42.0.1 dev eth0
10.42.0.0/24 dev eth0 scope link  src 10.42.0.184
10.42.0.0/16 via 10.42.0.1 dev eth0
10.192.129.0/24 dev net1 scope link  src 10.192.129.202
```

So between multus and route-override-cni there's a hole where this functionality needs to go.

**Comment by Lovett1991** [comment]
+1 Same problem on k8s. Can't resolve internal dns because the route is defaulting to the CNI dhcp network rather than the flannel network.

**Comment by bdkuhman** [comment]
Same here; k3s

Maybe related to #1187?
It looks like it's adding a default route for every interface.

I've managed to solve it in one container by running `ip route del` on startup, but not sure how to accomplish this in another container without any networking tools, DNS doesn't work.

**Comment by bdkuhman** [comment]
Having the same problem in k3s

I've worked around it in some pods by adding a route for dns to the cluster network

```bash
DEV=eth0 \
    && \
    ip route add $(grep nameserver /etc/resolv.conf | cut -d ' ' -f 2) \
    via $(netstat -r -n | grep $DEV | grep ^0 | tr -s " " | cut -d ' ' -f 2) \
    dev $DEV
```

Not sure how I'd solve this for containers that don't have `net-tools`/`iproute2` installed, though.

**Comment by Tobix99** [comment]
> Having the same problem in k3s
> 
> It appears that the service network (10.43.0.0/16 by default with k3s) isn't getting routed. I've worked around it in some pods by adding a route for it through the flannel interface
> 
> ```shell
> DEV=eth0 \
>     && \
>     ip route add 10.43.0.0/16 \
>     via $(netstat -r -n | grep $DEV | grep ^0 | tr -s " " | cut -d ' ' -f 2) \
>     dev $DEV
> ```
> 
> Just getting started with multus, so I'm not sure how to add this route through the CNI, or in containers that don't have the tools installed.

Hi @bdkuhman , is this still your method or did you find a better way? I'm also using k3s with flannel and have the same problem.

**Comment by bdkuhman** [comment]
>
> Hi @bdkuhman , is this still your method or did you find a better way? I'm also using k3s with flannel and have the same problem.

@Tobix99 Yep, still my workaround.
I did find it better to put into an init container, however.

```
      initContainers:
        - name: fixroutes
          image: jrecord/nettools
          imagePullPolicy: IfNotPresent
          env:
            - name: DEV
              value: eth0
          command:
            - '/bin/bash'
            - '-c'
            - ip route add 10.43.0.0/16 via $( ip route | grep -P $DEV\\s | grep default | tr -s ' ' | cut -d ' ' -f 3 ) dev $DEV
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
```

**Comment by hchyue** [comment]
i changed the command  a bit, it works. 

`initContainers:
  - name: fixroutes
    image: jrecord/nettools
    imagePullPolicy: IfNotPresent
    env:
    - name: DEV
      value: eth0
    command:
    - '/bin/bash'
    - '-c'
    - ip route add 10.42.0.0/16 via $( ip route | grep -P $DEV\\s | tr -s ' ' | cut -d ' ' -f 1 ) dev $DEV
    securityContext:
      capabilities:
        add:
        - NET_ADMIN`

**Comment by antoniomerlin** [comment]
> I changed the command a bit, it works.
> 
> ```
>   initContainers:
>   - name: fixroutes
>     image: jrecord/nettools
>     imagePullPolicy: IfNotPresent
>     env:
>     - name: DEV
>       value: eth0
>     command:
>     - '/bin/bash'
>     - '-c'
>     - ip route add 10.42.0.0/16 via $( ip route | grep -P $DEV\\s | tr -s ' ' | cut -d ' ' -f 1 ) dev $DEV
>     securityContext:
>       capabilities:
>         add:
>         - NET_ADMIN
> ```

This resolve the k8s internal DNS issue inside PODS but there is one issue if a service is added to the same pod on which this is configured then the POD is not accessible using that service <svc-name>.<namespace>.svc.cluster.local this dns name is able to resolve to its ip but on that ip getting timeout error.

**Comment by namtab00** [comment]
Has anyone managed to use multus to receive/send multicast UDP traffic (and multicast traffic ONLY) to/from a pod from/to outside the cluster  ?

I'm using k3s ( which [uses the different service cidr 10.43.0.0/16](https://docs.k3s.io/networking/basic-network-options#dual-stack-ipv4--ipv6-networking) ), on AlmaLinux 9.

With the _NetworkAttachmentDefinition_ ( _nad_ from here on ):

```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-nad
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "master": "ens3f0", # the host interface to bridge
      "type": "macvlan",
      "mtu": 1500,
      "capabilities": { "ips": true },
      "mode": "private",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.100.0/24",
        "rangeStart": "192.168.100.0",
        "rangeEnd": "192.168.100.3",
        "gateway": "192.168.100.1",
        "routes": [ { "dst": "224.0.0.0/4" } ]
      }
    }
```
, no multicast traffic reaches userland in a pod using the _nad_.

Do note the multicast-only route in the _ipam_ config.


It only works when routing all traffic with:
```yaml
...
config: |-
    {
      "cniVersion": "0.3.1",
      "master": "ens3f0",
      "type": "macvlan",
      "mtu": 1500,
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.100.0/24",
        "rangeStart": "192.168.100.0",
        "rangeEnd": "192.168.100.3",
        "gateway": "192.168.100.1",
        "routes": [ { "dst": "0.0.0.0/0" } ]
      }
    }
...
```
and using something similar to @bdkuhman's _initialContainer_ [setup](https://github.com/k8snetworkplumbingwg/multus-cni/issues/847#issuecomment-1989626928) to override the default route set by multus:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: multus-nad
spec:
  initContainers:
    - name: fixroutes
      image: jrecord/nettools
      imagePullPolicy: IfNotPresent
      command:
      - '/bin/bash'
      - '-c'
      - |
        ip route add 10.43.0.0/16 via 10.42.0.1 dev eth0 && \
        echo -e "\nip route after fix:"          && ip route
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
  containers:
  - name: my-pod
...
```

To what traffic do the routes specified in the _nad_ ipam config apply exactly?
- to traffic arriving from outside the cluster on the master interface specified in the _nad_ ?
- to traffic that entered the master interface then arrived to the multus virtual interface (cni0 on host) ?

Performing a tcpdump in the pod, I'm seeing the correct multicast traffic with:
- source: some IP on the LAN, outside the cluster
- destination: the destination multicast address, let's say `239.192.0.1`
, but without the default catchall route `0.0.0.0/0`, the traffic does not reach an userland app that correctly binds to `0.0.0.0` and joins the multicast group.

I'm trying to:
- avoid the initial container
- understand how ipam routes apply (I'm no Linux networking guru..)

Any help is greatly appreciated.


Sidenote for @bdkuhman's initial container command.
With your precise setup for the initial container, I was getting: ` Error: either "to" is duplicate, or "10.42.0.1" is a garbage.`

Debugging with:
```yaml
initContainers:
    - name: fixroutes
      image: jrecord/nettools
      imagePullPolicy: IfNotPresent
      env:
      - name: DEVICE
        value: eth0
      command:
      - '/bin/bash'
      - '-c'
      - |
        echo -e "ip route before fix:" && ip route && \
        echo -e "\ngrep:" && ip route | grep -P $DEVICE\\s && \
        echo -e "\ntr:" && ip route | grep -P $DEVICE\\s | tr -s ' ' && \
        echo -e "\ncut:" && ip route | grep -P $DEVICE\\s | tr -s ' ' | cut -d ' ' -f 1 && \
        echo -e "\nadding fix route:"  && \
        ip route add 10.43.0.0/16 via $( ip route | grep -P $DEV\\s | grep default | tr -s ' ' | cut -d ' ' -f 3 ) dev $DEV
        echo -e "\nip route after fix:" && ip route
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
```
yields:
```bash
ip route before fix:
default via 192.168.100.254 dev net1
default via 10.42.0.1 dev eth0
10.42.0.0/24 dev eth0 proto kernel scope link src 10.42.0.51
10.42.0.0/16 via 10.42.0.1 dev eth0
192.168.100.0/24 dev net1 proto kernel scope link src 192.168.100.100

grep:
default via 10.42.0.1 dev eth0
10.42.0.0/24 dev eth0 proto kernel scope link src 10.42.0.51
10.42.0.0/16 via 10.42.0.1 dev eth0

tr:
default via 10.42.0.1 dev eth0
10.42.0.0/24 dev eth0 proto kernel scope link src 10.42.0.51
10.42.0.0/16 via 10.42.0.1 dev eth0

cut:
default
10.42.0.0/24
10.42.0.0/16

adding fix route:
Error: either "to" is duplicate, or "10.42.0.1" is a garbage.

ip route after fix:
default via 192.168.100.254 dev net1
default via 10.42.0.1 dev eth0
10.42.0.0/24 dev eth0 proto kernel scope link src 10.42.0.51
10.42.0.0/16 via 10.42.0.1 dev eth0
192.168.100.0/24 dev net1 proto kernel scope link src 192.168.100.100
```

What exactly should that pipe sequence have yielded?

**Comment by bdkuhman** [comment]
@namtab00 
> 
> What exactly should that pipe sequence have yielded?

Did you forget to update the environment variable (`DEV` vs `DEVICE`)?
It should yield the ip of the default route for that device. 

```
ip route
default via 192.168.100.254 dev net1
default via 10.42.3.1 dev eth0
192.168.100.0/24 dev net1 proto kernel scope link src 192.168.100.100
10.42.0.0/16 via 10.42.3.1 dev eth
10.42.3.0/24 dev eth0 scope link  src 10.42.3.127

ip route | grep -P eth0\\s
default via 10.42.3.1 dev eth0
10.42.0.0/16 via 10.42.3.1 dev eth0
10.42.3.0/24 dev eth0 scope link  src 10.42.3.127

 ip route | grep -P eth0\\s | grep default
default via 10.42.3.1 dev eth0

#think I had some whitespace issues when this was using netstat which the tr fixes
ip route | grep -P eth0\\s | grep default | tr -s ' ' 
default via 10.42.3.1 dev eth0

cut -f 3
10.42.3.1
```

If `$DEV` / `$DEVICE` is empty/ambiguous, then it pulls both default routes, and you get 

`ip route add ip via 192.168.100.254 10.42.3.1 dev device`

where it should only have 1 ip (the default gw to the k8s pod network)

**Comment by namtab00** [comment]
@bdkuhman doh! ... I clearly spent too much time debugging multus with multiple setups and jumbled up the env var name (DEVICE / DEV)

with the following initiContainer the IP for the default route gets correctly added:
```yaml
initContainers:
    - name: fixroutes
      image: jrecord/nettools
      imagePullPolicy: IfNotPresent
      env:
        - name: DEVICE
          value: eth0
      command:
      - '/bin/bash'
      - '-c'
      - |
        echo -e "ip route before fix:"      && ip route && \
        echo -e "\ngrep:"                   && ip route | grep -P $DEVICE\\s && \
        echo -e "\ntr:"                     && ip route | grep -P $DEVICE\\s | tr -s ' ' && \
        echo -e "\ncut:"                    && ip route | grep -P $DEVICE\\s | tr -s ' ' | cut -d ' ' -f 3 && \
        echo -e "\nadding route to k3s services subnet" && \
        ip route add 10.43.0.0/16 via $( ip route | grep -P $DEVICE\\s | grep default | tr -s ' ' | cut -d ' ' -f 3 ) dev $DEVICE && \
        echo -e "\nip route after fix:"     && ip route
      securityContext:
        capabilities:
          add:
          - NET_ADMIN
```

Any chance you have a hint for the first issue, the routing of multicast only ( `224.0.0.0/4` ) through the multus added NIC (`net1`), while leaving all other traffic through the default pod NIC ('eth0') ?

I'm trying to understand what the ipam routes refer to: traffic leaving the pod, or entering the pod?
If it's for traffic leaving the pod, I can't wrap my head around why incoming multicast traffic is not seen in userland if the `0.0.0.0/0` route is not set...
