### ISSUE TITLE
Should NIC name of all nodes have to be same??

### ISSUE THREAD

**Issue by JuHyung-Son** [k8snetworkplumbingwg/multus-cni#871]
This is my net def.

and I wonder if some node`s nic name is not `enp104s0f1` then that node can not use additional cni???

So should I have to make all nodes’ nic name same? or this there other way?

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "mode": "bridge",
      "master": "enp104s0f1",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.50",
        "rangeEnd": "192.168.1.254",
        "gateway": "192.168.1.255"
      }
    }'
```
