### ISSUE TITLE
how to define a static multus configuration file to use?

### ISSUE THREAD

**Issue by yee379** [k8snetworkplumbingwg/multus-cni#911]
i would like to use a couple of CNI's as delegates for Multus. However, my default CNI (calico) defines `10-calico.conf`, whilst my 'secondary' CNI (cilium) uses `05-cilium.conf`. When i specify `-multus-conf-file=auto` in the command line, Multus will always pick cilium as my default network - when i actually want calico.

save trying to get cilium to write a different CNI file to avoid this issue, i attempted to simply have Multus pick up a default configuration file.

so i write a kustomize `patchesStrateficMerge` that mounts the json configuration from a `configMap` and override the container `args` (both provide below). it essentially runs:

```
# /usr/src/multus-cni/bin/multus-daemon  -cni-version=0.3.1 -cni-config-dir=/host/etc/cni/net.d -multus-conf-file=/tmp/etc/cni/net.d/00-multus.conf  -multus-log-to-stderr=true -multus-log-level=verbose
```

however, i'm greeted with:

```
2022-09-13T03:48:09Z [error] failed to copy the user provided configuration /tmp/etc/cni/net.d/00-multus.conf: error copying file: write /tmp/etc/cni/net.d/00-multus.conf: copy_file_range: bad file descriptor
```

and the file under `(/host)/etc/cni/net.d/00-multus.conf` is zero-length.

This is with a kinda cluster.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: kube-multus
        args:
        - -cni-version=0.3.1
        - -cni-config-dir=/host/etc/cni/net.d
        - -multus-conf-file=/tmp/etc/cni/net.d/00-multus.conf
        - -multus-log-to-stderr=true
        - -multus-log-level=verbose
        volumeMounts:
        - mountPath: /tmp/etc/cni/net.d/00-multus.conf
          name: multus-cfg
          subPath: 00-multus.conf
      volumes:
      - name: multus-cfg
        configMap:
          name: multus-cni-config
          items:
          - key: cni-conf.json
            path: 00-multus.conf
```

and the configmap:

```kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  cni-conf.json: |
    {
      "capabilities": {
        "bandwidth": true,
        "portMappings": true
      },
      "cniVersion": "0.3.1",
      "delegates": [
        {
          "cniVersion": "0.3.1",
          "name": "k8s-pod-network",
          "plugins": [
            {
              "container_settings": {
                "allow_ip_forwarding": false
              },
              "datastore_type": "kubernetes",
              "ipam": {
                "assign_ipv4": "true",
                "assign_ipv6": "false",
                "type": "calico-ipam"
              },
              "kubernetes": {
                "k8s_api_root": "https://10.96.0.1:443",
                "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
              },
              "log_file_path": "/var/log/calico/cni/cni.log",
              "log_level": "Info",
              "mtu": 0,
              "nodename_file_optional": false,
              "policy": {
                "type": "k8s"
              },
              "type": "calico"
            },
            {
              "capabilities": {
                "bandwidth": true
              },
              "type": "bandwidth"
            },
            {
              "capabilities": {
                "portMappings": true
              },
              "snat": true,
              "type": "portmap"
            }
          ]
        }
      ],
      "logLevel": "verbose",
      "logToStderr": true,
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
      "name": "multus-cni-network",
      "type": "multus"
    }
```
