### ISSUE TITLE
how to get dummy kernel interface inside a pod with SRIOV-DPDK in userspace?

### ISSUE THREAD

**Issue by ankush06** [k8snetworkplumbingwg/multus-cni#913]
Hi,

I am trying to get a dummy kernel interface inside a pod, so user application can bind to SRIOV-DPDK interface. I can see the VF is getting assign to a pod but interface is not created. Below is my sample Network-Attach-definition and test-pod. 
 `Network-Attach-definition.yaml`
     

          apiVersion: k8s.cni.cncf.io/v1
          kind: NetworkAttachmentDefinition
          metadata:
              name: sriov-cuup-cp1-dpdk
              annotations:
                   k8s.v1.cni.cncf.io/resourceName: "intel.com/pci_sriov_net_dpdknet0"
           spec:
                config: '{
                "cniVersion": "0.3.1",
                "name": "sriov-cuup-cp1-dpdk",
                 "plugins": [
                        {
                           "type": "sriov",
                           "vlan": 2000,
                            "ipam": {
                                 "type": "host-local",
                                  "ranges": [
                                       [
                                          {
                                               "subnet": "11.199.121.0/24",
                                               "rangeStart": "11.199.121.3",
                                               "rangeEnd": "11.199.121.9",
                                               "gateway": "11.199.121.254"
                                          }
                                       ]
                                    ]
                               }
                           }
                        ]
                     }'

            ---
           apiVersion: k8s.cni.cncf.io/v1
           kind: NetworkAttachmentDefinition

          metadata:
          name: sriov-cuup-cp1-phys2
          annotations:
          k8s.v1.cni.cncf.io/resourceName: "intel.com/pci_sriov_net_physnet0"
          spec:
          config: '{
                 "cniVersion": "0.3.1",
                 "name": "sriov-cuup-cp1-phys2",
                 "plugins": [
                     {
                       "type": "sriov",
                       "vlan": 2001,
                       "ipam": {
                       "type": "host-local",
                       "ranges": [
                             [
                                {
                                   "subnet": "12.196.121.0/24",
                                   "rangeStart": "12.196.121.3",
                                    "rangeEnd": "12.196.121.9",
                                   "gateway": "12.196.121.254"
                               }
                            ]
                        ]
                      }
                  },
                 {
                   "name": "brsbr2",
                   "type": "sbr"
                  }
               ]
            }'

                 

`test-pod.yaml
` 
```
 apiVersion: v1
 kind: Pod
 metadata:
  name: busybox1
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
       { "name": "sriov-cuup-cp1-dpdk", "interface": "netcp1" },
       { "name": "sriov-cuup-cp1-phys2", "interface": "netcp2" }
    ]'
 spec:
  containers:
  - image: 10.222.20.1:31505/danm/busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox1
    resources:
      requests:
        intel.com/pci_sriov_net_dpdknet0: '1'
        intel.com/pci_sriov_net_physnet0: '1'
      limits:
        intel.com/pci_sriov_net_dpdknet0: '1'
        intel.com/pci_sriov_net_physnet0: '1'

```
I can see the PCI address populated inside a pod 
 ```
printenv | grep PCI
PCIDEVICE_INTEL_COM_PCI_SRIOV_NET_DPDKNET0=0000:8a:03.2
PCIDEVICE_INTEL_COM_PCI_SRIOV_NET_PHYSNET0=0000:8a:02.0
```

But, SRIOV-DPDK based interface (netcp1) is not created.
```
ifconfig
eth0      Link encap:Ethernet  HWaddr D2:EE:6B:3B:A3:5C
          inet addr:192.168.23.175  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::d0ee:6bff:fe3b:a35c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12 errors:0 dropped:1 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:446 (446.0 B)  TX bytes:936 (936.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

netcp2    Link encap:Ethernet  HWaddr 0A:D6:66:01:00:08
          inet addr:12.196.121.4  Bcast:12.196.121.255  Mask:255.255.255.0
          inet6 addr: fe80::8d6:66ff:fe01:8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:538 (538.0 B)
```

Is there any additional plugin to support the interface creation in kernel space? I can see the DANM documentation which provides support for such dummy interface creation for DPDK: https://github.com/nokia/danm/blob/master/user-guide.md#dpdk-support

how can i achieve a similar functionality with Multus?
