### ISSUE TITLE
delegate add endpoint: does not handle `NetConfList` CNI configurations

### ISSUE THREAD

**Issue by maiqueb** [k8snetworkplumbingwg/multus-cni#914]
**What happend**:
When trying to invoke the `delegate` endpoint with a CNI configuration featuring `NetConfList` throws the following error:
```
error configuring pod [default/macvlan1-worker1] networking: error in converting the raw bytes to conf: error parsing configuration: missing 'type'
```

**What you expected to happen**:
The requested delegate should be added.

**How to reproduce it (as minimally and precisely as possible)**:
Try the [sample delegate project](https://github.com/s1061123/multus-delegate-sample) to add a delegate with the following configuration:
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan1-config
spec:
  config: '{
            "cniVersion": "0.4.0",
            "plugins": [
                {
                    "type": "macvlan",
                    "capabilities": { "ips": true },
                    "master": "eth1",
                    "mode": "bridge",
                    "ipam": {
                        "type": "static"
                    }
                }, {
                    "type": "tuning"
                } ]
        }'
```

The pod spec I've used looks like:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: macvlan1-worker1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            {
                "name": "macvlan1-config",
                "ips": [ "10.1.1.11/24" ]
            }
    ]'
  labels:
    app: macvlan
spec:
  containers:
    - name: macvlan-worker1
      image: docker.io/library/alpine:latest
      command: ["/bin/sleep", "10000"]
```

**Anything else we need to know?**:
When invoking the same endpoint with a configuration using a `NetConf` CNI configuration, it **does** work as expected.

This happens because the server code **always** [unmarshalls the configuration](https://github.com/k8snetworkplumbingwg/multus-cni/blob/505ab4567c743043cba534c61981c508180fbfd3/pkg/server/server.go#L95) as `NetConf`. 

It should check if the configuration is a `NetConfList` or `NetConf` then unmarshal into the corresponding struct.

**Environment**:
Multus in thick plugin mode
