### ISSUE TITLE
Multus fails to copy user provided configuration

### ISSUE THREAD

**Issue by reversecipher** [k8snetworkplumbingwg/multus-cni#931]
**What happend**:

Multus daemon fails to copy user provided configuration:

`[error] failed to copy the user provided configuration /tmp/multus-conf/00-multus.conf: error copying file - copied only 0 bytes out of 1703`

Multus Daemonset (relevant parts):

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  template:
    spec:
      containers:
        - name: kube-multus
          image: ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick
          command: [ "/usr/src/multus-cni/bin/multus-daemon" ]
          args:
            - "-cni-version=0.3.1"
            - "-cni-config-dir=/host/etc/cni/net.d"
            - "-multus-autoconfig-dir=/host/etc/cni/net.d"
            - "-multus-log-to-stderr=true"
            - "-multus-log-level=verbose"
            - "-multus-conf-file=/tmp/multus-conf/00-multus.conf"
          volumeMounts:
            - name: custom-config
              mountPath: /tmp/multus-conf
      volumes:
        - name: custom-config
          configMap:
            name: multus-custom-config
            items:
            - key: 00-multus.conf
              path: 00-multus.conf
```

ConfigMap:

```
Name:         multus-custom-config
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
00-multus.conf:
----
{
    "capabilities": {
        "bandwidth": true,
        "portMappings": true
    },
    "cniVersion": "0.3.1",
    "logLevel": "verbose",
    "logToStderr": true,
    "name": "multus-cni-network",
    "type": "multus-shim",
    "delegates": [
        {
            "name": "k8s-pod-network",
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "calico",
                    "datastore_type": "kubernetes",
                    "mtu": 0,
                    "nodename_file_optional": false,
                    "log_level": "Info",
                    "log_file_path": "/var/log/calico/cni/cni.log",
                    "ipam": {
                        "type": "calico-ipam",
                        "assign_ipv4": "true",
                        "assign_ipv6": "false"
                    },
                    "container_settings": {
                        "allow_ip_forwarding": false
                    },
                    "policy": {
                        "type": "k8s"
                    },
                    "kubernetes": {
                        "k8s_api_root": "https://10.96.0.1:443",
                        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
                    }
                },
                {
                    "type": "bandwidth",
                    "capabilities": {
                        "bandwidth": true
                    }
                },
                {
                    "type": "portmap",
                    "snat": true,
                    "capabilities": {
                        "portMappings": true
                    }
                }
            ]
        }
    ]
}


BinaryData
====

Events:  <none>
```

I also tried to mount the configuration using hostPath but the same error occurs.

**What you expected to happen**:

Multus should copy the user provided configuration to `/etc/cni/net.d/`

**Anything else we need to know?**:

Multus was installed following the quickstart guide (thick plugin).

**Environment**:

- Multus version: `ghcr.io/k8snetworkplumbingwg/multus-cni:snapshot-thick                                                                           application/vnd.docker.distribution.manifest.list.v2+json sha256:89d1815b954e53b8fed00dd77ae8c0ab798ffc3a52c47180f2ee0a58b94fc1a3 85.4 MiB  linux/amd64`
- Kubernetes version: `Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}`
- Primary CNI for Kubernetes cluster: Calico
- OS (e.g. from /etc/os-release): Rocky Linux 8.6
