### ISSUE TITLE
[BUG] cannot create pod requiring resources in the thick plugin arch

### ISSUE THREAD

**Issue by maiqueb** [k8snetworkplumbingwg/multus-cni#944]
**What happend**:
Fails to create a pod requiring resources; it hangs in `ContainerCreating` state.

**What you expected to happen**:
Pod should be created. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Have [macvtap-cni](https://github.com/kubevirt/macvtap-cni/) installed in the cluster.
2. Provision the following NAD
```yaml
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/eth0
    creationTimestamp: "2022-10-31T09:03:27Z"
    generation: 1
    name: macvtap0
    namespace: cluster-network-addons
    resourceVersion: "2443"
    uid: af896e29-101b-48d5-8e89-8f3391c1e1fa
  spec:
    config: '{ "cniVersion": "0.3.1", "name": "macvtap0", "type": "macvtap"}'
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
3. Provision the following pod; it'll hang in `ContainerCreating`
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: macvtap0
  name: megapod
  namespace: cluster-network-addons
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 999999
    image: alpine
    imagePullPolicy: Always
    name: tinycontainer
    resources:
      limits:
        macvtap.network.kubevirt.io/eth0: "1"
      requests:
        macvtap.network.kubevirt.io/eth0: "1"
```

**Anything else we need to know?**:
The following event can be seen:
```
ERRORED: error configuring pod [cluster-network-addons/megapod] networking: Multus: [cluster-network-addons/megapod/86803eb1-0b17-464e-bd04-572fb0121445]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: failed to get a ResourceClient instance: getKubeletClient: error getting pod resources from client: getPodResources: failed to list pod resources, &{0xc000402a80}.Get(_) = _, rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix unix:/var/lib/kubelet/pod-resources/kubelet.sock: connect: no such file or directory"
```

Despite that, that path is available within the multus pod:
```bash
kubectl exec -ncluster-network-addons multus-j85fz -- ls -la /var/lib/kubelet/pod-resources/kubelet.sock
Defaulted container "kube-multus" out of: kube-multus, install-multus-binary (init)
srwxr-xr-x. 1 root root 0 Oct 31 08:47 /var/lib/kubelet/pod-resources/kubelet.sock
```

This bug is [preventing](https://github.com/kubevirt/cluster-network-addons-operator/pull/1433/) KubeVirt from pulling the thick plugin via its network operator (the e2e tests of depending PRs are failing). 

This in turn blocks the hotplug feature for KubeVirt.

**Environment**:

- Multus version 
  image path and image ID (from 'docker images'): `sha256:1c909e4d03006a7c1acde5e0953cd607db0dd34fca680cab3dc9fcfc29ff9174`
- Kubernetes version (use `kubectl version`): `1.24.1`
- Primary CNI for Kubernetes cluster: calico
- OS (e.g. from /etc/os-release): fedora 36
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)
