### ISSUE TITLE
Device-info-spec missing in network-status when using the "plugins" filed in the NAD's CNI Spec.

### ISSUE THREAD

**Issue by joelcheison** [k8snetworkplumbingwg/multus-cni#973]
**What happened**:

The device-info spec appears in the pod's network-status annotation when the NAD config only contains a single plugin using the "type" filed in the cni spec.

```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/pci_sriov_net_f1
  name: test-net
  namespace: test
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "test",
    "type": "sriov",
```
However when the "plugins" list of the cni spec (https://github.com/containernetworking/cni/blob/main/SPEC.md) is used for the NAD to invoke more than one plugin in a NAD, the device-info-spec is missing in the pod network-status annotation

```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/pci_sriov_net_f1
  name: test-net
  namespace: test
spec:
  config: '{
   "cniVersion" : "0.3.1",
   "name" : "networking-f1c",
   "plugins" : [
      {
         "ipam" : {
            "type" : "static"
         },
         "name" : "test",
         "type" : "sriov",
         "vlan" : 821,
         "spoofchk": "on",
         "trust":"off",
         "link_state": "auto"
      },
      {
         "type": "tuning",
         "sysctl": { 
            "net.ipv6.conf.test.disable_ipv6": "1"
         }
       }
   ]
}'
```

**What you expected to happen**:
Device-info-spec to be present in pod annotation even when the "plugins" list of cni spec is used.

**How to reproduce it (as minimally and precisely as possible)**:
Create a NAD using the plugins field, use sriov-cni as one plugin and tuning cni as the other.

**Anything else we need to know?**:

**Environment**:

- Multus version 
  v3.8
- Kubernetes version (use `kubectl version`): v1.24.0
